(()=>{'use strict';
const path=location.pathname.replace(/index\.html$/,'');
if(path!=='/money-resilience/'&&path!=='/money-resilience')return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const reduce=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
const num=v=>{const n=Number(String(v||'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0};
const capture=(name,props={})=>{try{window.scosCapture?.(name,props)}catch(_){}};

const css=document.createElement('style');css.id='mr-experience-v3-style';css.textContent=`
body.mr-vnext-body .mr-core-wrap{isolation:isolate}body.mr-vnext-body .mr-focus-glow{--fx:50%;--fy:50%;--fi:.2;position:absolute;z-index:5;left:var(--fx);top:var(--fy);width:42%;aspect-ratio:1;border-radius:50%;transform:translate(-50%,-50%) scale(calc(.72 + var(--fi)*.45));background:radial-gradient(circle,rgba(124,231,194,calc(.05 + var(--fi)*.11)) 0,rgba(124,231,194,calc(.02 + var(--fi)*.05)) 36%,transparent 68%);filter:blur(calc(2px + var(--fi)*5px));opacity:0;transition:left .36s var(--ease),top .36s var(--ease),transform .36s var(--ease),opacity .22s ease;pointer-events:none}body.mr-vnext-body .mr-core-wrap.mr-focus-on .mr-focus-glow{opacity:1}
body.mr-vnext-body .mr-pressure-focus-chip{position:absolute;z-index:12;left:50%;bottom:3%;transform:translate(-50%,8px);display:flex;align-items:center;gap:7px;min-width:94px;max-width:78%;height:28px;padding:0 10px;border:1px solid rgba(124,231,194,.14);border-radius:999px;background:rgba(8,14,15,.82);backdrop-filter:blur(14px);box-shadow:0 10px 30px rgba(0,0,0,.22);opacity:0;pointer-events:none;transition:opacity .2s ease,transform .28s var(--ease)}body.mr-vnext-body .mr-core-wrap.mr-focus-on .mr-pressure-focus-chip{opacity:1;transform:translate(-50%,0)}body.mr-vnext-body .mr-pressure-focus-chip i{width:5px;height:5px;border-radius:50%;background:var(--mint);box-shadow:0 0 0 4px rgba(124,231,194,.055)}body.mr-vnext-body .mr-pressure-focus-chip b{font-size:8px;font-weight:560;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}body.mr-vnext-body .mr-pressure-focus-chip span{margin-left:auto;color:#71847f;font-size:7px;font-variant-numeric:tabular-nums}
body.mr-vnext-body .mr-pressure-dot{pointer-events:auto;cursor:pointer}body.mr-vnext-body .mr-pressure-dot.selected{outline:1px solid rgba(242,244,239,.34);outline-offset:5px;z-index:3}body.mr-vnext-body .mr-pressure-field.has-selection .mr-pressure-dot:not(.selected){opacity:.22!important}.mr-factor.mr-factor-focus{border-color:rgba(124,231,194,.2)!important;background:rgba(124,231,194,.035)!important;transform:translateY(-1px)}
body.mr-vnext-body .mr-shock-wrap.mr-scrubbing{filter:drop-shadow(0 7px 20px rgba(124,231,194,.06))}body.mr-vnext-body .mr-shock-wrap.mr-scrubbing .mr-dial-labels button.active{transform:scale(1.035)}body.mr-vnext-body .mr-swipe-hint{display:flex;align-items:center;justify-content:center;gap:5px;height:14px;margin-top:2px;color:#536762;font-size:5.5px;letter-spacing:.12em;text-transform:uppercase;opacity:.7;transition:opacity .2s ease}.mr-swipe-hint i{width:16px;height:1px;background:linear-gradient(90deg,transparent,rgba(124,231,194,.35),transparent)}.mr-shock-wrap.mr-scrubbing .mr-swipe-hint{opacity:1;color:#76988d}
body.mr-vnext-body .mr-result-peek-backdrop{position:fixed;z-index:78;inset:0;background:rgba(2,7,8,.42);backdrop-filter:blur(3px);opacity:0;pointer-events:none;transition:opacity .22s ease}body.mr-vnext-body .mr-result-peek-backdrop.open{opacity:1;pointer-events:auto}body.mr-vnext-body .mr-result-peek{position:fixed;z-index:79;left:10px;right:10px;bottom:calc(10px + env(safe-area-inset-bottom));padding:9px;border:1px solid rgba(208,230,224,.12);border-radius:22px;background:linear-gradient(160deg,rgba(16,25,25,.97),rgba(8,14,15,.98));box-shadow:0 30px 90px rgba(0,0,0,.45);transform:translateY(calc(100% + 24px));opacity:.98;transition:transform .34s var(--ease);display:none}.mr-result-peek.open{transform:translateY(0)}.mr-result-peek-handle{width:34px;height:3px;border-radius:999px;background:rgba(255,255,255,.14);margin:2px auto 9px}.mr-result-peek-grid{display:grid;grid-template-columns:1.2fr 1fr 1fr;gap:6px}.mr-result-peek-grid div{min-width:0;padding:10px;border:1px solid rgba(208,230,224,.075);border-radius:14px;background:rgba(255,255,255,.014)}.mr-result-peek-grid div:first-child{background:linear-gradient(135deg,rgba(124,231,194,.07),rgba(255,255,255,.012));border-color:rgba(124,231,194,.12)}.mr-result-peek-grid small{display:block;color:#637671;font-size:5.5px;letter-spacing:.12em}.mr-result-peek-grid b{display:block;margin-top:4px;font-size:13px;font-weight:560;letter-spacing:-.035em;font-variant-numeric:tabular-nums;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.mr-result-peek-grid div:first-child b{font-size:24px}.mr-result-peek-foot{margin-top:6px;display:grid;grid-template-columns:1fr 1fr;gap:6px}.mr-result-peek-foot button{height:36px;border:1px solid rgba(208,230,224,.09);border-radius:12px;background:rgba(255,255,255,.014);color:#aabcb6;font-size:7px;letter-spacing:.08em}.mr-result-peek-foot button.primary{border-color:rgba(124,231,194,.16);background:rgba(124,231,194,.055);color:#dff5ed}
@media(min-width:721px){body.mr-vnext-body .mr-result-peek-backdrop,body.mr-vnext-body .mr-result-peek{display:none!important}body.mr-vnext-body .mr-swipe-hint{opacity:.42}}
@media(max-width:720px){body.mr-vnext-body .mr-result-peek{display:block}body.mr-vnext-body .mr-mobile-state-strip{cursor:pointer}body.mr-vnext-body .mr-pressure-focus-chip{bottom:-2%;height:26px;max-width:84%}}
@media(prefers-reduced-motion:reduce){body.mr-vnext-body .mr-focus-glow,body.mr-vnext-body .mr-pressure-focus-chip,body.mr-vnext-body .mr-result-peek-backdrop,body.mr-vnext-body .mr-result-peek,body.mr-vnext-body .mr-swipe-hint{transition:none!important}}
`;
document.head.appendChild(css);

let tries=0;const boot=setInterval(()=>{tries++;if($('.mr-core-card .mr-core-wrap')&&$('#mrFactorLegend')&&$('#mrScenario')){clearInterval(boot);init()}else if(tries>120)clearInterval(boot)},80);

function init(){addPressureFocus();addSwipeStress();addMobileResultPeek();capture('money_resilience_experience_v3_loaded',{motion:reduce?'reduced':'full'})}
function currentLang(){return document.documentElement.lang==='en'?'en':'ja'}
function metrics(){const tiles=$$('#mrResultGrid .mr-result-tile');const get=(rx,idx)=>{const hit=tiles.find(t=>rx.test(($('small',t)?.textContent||'').trim()));return ($('b',hit||tiles[idx])?.textContent||'—').trim()};return{score:($('[data-core="main"] [data-core-score]')?.textContent||'—').trim(),shock:get(/shock|月間/i,1),runway:get(/runway|現金/i,2),exposure:get(/exposure|最大/i,3),next:get(/next|check|確認/i,4)}}

function addPressureFocus(){const core=$('.mr-core-card .mr-core-wrap'),field=$('.mr-pressure-field',core),legend=$('#mrFactorLegend');if(!core||!legend)return;if(!$('.mr-focus-glow',core)){const glow=document.createElement('i');glow.className='mr-focus-glow';core.appendChild(glow);const chip=document.createElement('div');chip.className='mr-pressure-focus-chip';chip.innerHTML='<i></i><b>—</b><span>—</span>';core.appendChild(chip)}
 const positions=[[50,2],[88,25],[90,73],[50,98],[10,73],[12,25]];let selected=-1,timer;
 function factorData(i){const el=$$('.mr-factor',legend)[i];return{el,name:($('span',el)?.textContent||`F${i+1}`).trim(),value:clamp(num($('b',el)?.textContent),0,100)}}
 function focus(i,sticky=false){const all=$$('.mr-factor',legend),dots=field?$$('.mr-pressure-dot',field):[];if(i<0||i>=all.length){selected=-1;core.classList.remove('mr-focus-on');field?.classList.remove('has-selection');dots.forEach(d=>d.classList.remove('selected'));all.forEach(x=>x.classList.remove('mr-factor-focus'));return}selected=i;const f=factorData(i),p=positions[i]||[50,50],glow=$('.mr-focus-glow',core),chip=$('.mr-pressure-focus-chip',core);glow.style.setProperty('--fx',p[0]+'%');glow.style.setProperty('--fy',p[1]+'%');glow.style.setProperty('--fi',String(Math.max(.12,f.value/100)));$('b',chip).textContent=f.name;$('span',chip).textContent=Math.round(f.value)+'%';core.classList.add('mr-focus-on');field?.classList.add('has-selection');dots.forEach((d,n)=>d.classList.toggle('selected',n===i));all.forEach((x,n)=>x.classList.toggle('mr-factor-focus',n===i));clearTimeout(timer);if(!sticky)timer=setTimeout(()=>focus(-1),1500)}
 if(field)field.addEventListener('click',e=>{const d=e.target.closest('.mr-pressure-dot');if(!d)return;const i=Number(d.dataset.i);focus(i,true);capture('money_resilience_pressure_focus',{factor_index:i})});
 legend.addEventListener('click',e=>{const f=e.target.closest('.mr-factor');if(!f)return;const i=$$('.mr-factor',legend).indexOf(f);focus(i,true);capture('money_resilience_pressure_focus',{factor_index:i,source:'legend'})});
 core.addEventListener('pointerleave',()=>{if(selected>=0&&innerWidth>720)focus(-1)});
 core.addEventListener('dblclick',()=>focus(-1));
 new MutationObserver(()=>{if(selected>=0)focus(selected,true)}).observe(legend,{subtree:true,childList:true,characterData:true,attributes:true});
}

function addSwipeStress(){const wrap=$('.mr-shock-wrap'),slider=$('#mrScenario');if(!wrap||!slider)return;if(!$('.mr-swipe-hint',wrap)){const hint=document.createElement('div');hint.className='mr-swipe-hint';hint.innerHTML='<i></i><span>SWIPE STRESS</span><i></i>';wrap.appendChild(hint)}
 let startX=0,startV=0,active=false,moved=false;
 function setValue(v,source){const next=clamp(Math.round(v),0,2);if(Number(slider.value)===next)return;slider.value=String(next);slider.dispatchEvent(new Event('input',{bubbles:true}));capture('money_resilience_stress_swipe',{scenario:next,source})}
 wrap.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;active=true;moved=false;startX=e.clientX;startV=Number(slider.value)||0;wrap.classList.add('mr-scrubbing');try{wrap.setPointerCapture(e.pointerId)}catch(_){}});
 wrap.addEventListener('pointermove',e=>{if(!active)return;const dx=e.clientX-startX;if(Math.abs(dx)>8)moved=true;const width=Math.max(140,wrap.getBoundingClientRect().width),virtual=startV+(dx/(width*.34));const preview=clamp(Math.round(virtual),0,2);if(preview!==Number(slider.value)){slider.value=String(preview);slider.dispatchEvent(new Event('input',{bubbles:true}))}});
 function end(e){if(!active)return;active=false;wrap.classList.remove('mr-scrubbing');const dx=e.clientX-startX;if(moved&&Math.abs(dx)>22){const dir=dx>0?1:-1;setValue(startV+dir,'gesture')}else setValue(Number(slider.value),'snap');try{wrap.releasePointerCapture(e.pointerId)}catch(_){}}
 wrap.addEventListener('pointerup',end);wrap.addEventListener('pointercancel',end);
}

function addMobileResultPeek(){if($('.mr-result-peek'))return;const backdrop=document.createElement('div');backdrop.className='mr-result-peek-backdrop';const sheet=document.createElement('section');sheet.className='mr-result-peek';sheet.setAttribute('role','dialog');sheet.setAttribute('aria-modal','true');sheet.setAttribute('aria-label','Money Resilience result');sheet.innerHTML='<div class="mr-result-peek-handle"></div><div class="mr-result-peek-grid"><div><small>SCORE</small><b data-peek="score">—</b></div><div><small>SHOCK</small><b data-peek="shock">—</b></div><div><small>RUNWAY</small><b data-peek="runway">—</b></div></div><div class="mr-result-peek-foot"><button type="button" data-peek-action="result">RESULT</button><button type="button" class="primary" data-peek-action="close">CLOSE</button></div>';document.body.append(backdrop,sheet);
 let open=false,startY=0,drag=false;
 function sync(){const m=metrics();Object.entries(m).forEach(([k,v])=>{const el=$(`[data-peek="${k}"]`,sheet);if(el)el.textContent=v})}
 function toggle(v){open=!!v;sync();sheet.classList.toggle('open',open);backdrop.classList.toggle('open',open);document.body.classList.toggle('mr-peek-open',open);capture('money_resilience_mobile_result_sheet',{state:open?'open':'close'})}
 const bar=$('.mr-mobile-state-strip');if(bar){bar.addEventListener('click',e=>{if(innerWidth>720)return;e.preventDefault();toggle(true)},{capture:true})}
 backdrop.addEventListener('click',()=>toggle(false));sheet.addEventListener('click',e=>{const a=e.target.closest('[data-peek-action]');if(!a)return;if(a.dataset.peekAction==='close')toggle(false);else{toggle(false);setTimeout(()=>$('.mr-result-card')?.scrollIntoView({behavior:reduce?'auto':'smooth',block:'center'}),30)}});
 sheet.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;drag=true;startY=e.clientY;try{sheet.setPointerCapture(e.pointerId)}catch(_){}});sheet.addEventListener('pointermove',e=>{if(!drag)return;const dy=Math.max(0,e.clientY-startY);sheet.style.transform=`translateY(${Math.min(120,dy)}px)`});sheet.addEventListener('pointerup',e=>{if(!drag)return;drag=false;const dy=e.clientY-startY;sheet.style.transform='';if(dy>64)toggle(false);try{sheet.releasePointerCapture(e.pointerId)}catch(_){}});
 const targets=[$('[data-core="main"] [data-core-score]'),$('#mrResultGrid')].filter(Boolean);targets.forEach(el=>new MutationObserver(()=>requestAnimationFrame(sync)).observe(el,{subtree:true,childList:true,characterData:true,attributes:true}));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&open)toggle(false)});sync();
}
})();