(()=>{'use strict';
const path=location.pathname.replace(/index\.html$/,'');
if(path!=='/'&&path!=='/money-resilience/'&&path!=='/money-resilience')return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const reduce=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));
const capture=(name,props={})=>{try{window.scosCapture?.(name,props)}catch(_){}};
const num=v=>{const n=Number(String(v||'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0};

const css=document.createElement('style');css.id='mr-experience-v2-style';css.textContent=`
body.mr-vnext-body .mr-live-chain{margin-top:10px;display:grid;grid-template-columns:minmax(0,1fr) 20px minmax(0,1fr) 20px minmax(0,1fr);align-items:center;gap:6px;padding:8px;border:1px solid rgba(208,230,224,.09);border-radius:16px;background:linear-gradient(135deg,rgba(125,184,233,.035),rgba(124,231,194,.028));overflow:hidden}
body.mr-vnext-body .mr-live-node{min-width:0;padding:8px 9px;border:1px solid rgba(208,230,224,.075);border-radius:12px;background:rgba(255,255,255,.012);transition:transform .28s var(--ease),border-color .28s var(--ease),background .28s var(--ease)}body.mr-vnext-body .mr-live-node small{display:flex;align-items:center;gap:5px;color:#637571;font-size:6px;letter-spacing:.14em;text-transform:uppercase;white-space:nowrap}body.mr-vnext-body .mr-live-node small i{width:4px;height:4px;border-radius:50%;background:#5f726d}body.mr-vnext-body .mr-live-node b{display:block;margin-top:4px;font-size:13px;line-height:1.05;font-weight:560;letter-spacing:-.03em;font-variant-numeric:tabular-nums;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}body.mr-vnext-body .mr-live-node span{display:block;margin-top:3px;color:#70837e;font-size:7px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
body.mr-vnext-body .mr-live-node[data-kind="market"] small i{background:var(--blue);box-shadow:0 0 0 4px rgba(125,184,233,.05)}body.mr-vnext-body .mr-live-node[data-kind="pressure"] small i{background:var(--amber);box-shadow:0 0 0 4px rgba(227,189,114,.05)}body.mr-vnext-body .mr-live-node[data-kind="core"] small i{background:var(--mint);box-shadow:0 0 0 4px rgba(124,231,194,.06)}body.mr-vnext-body .mr-live-link{height:1px;position:relative;background:linear-gradient(90deg,rgba(125,184,233,.18),rgba(124,231,194,.38));overflow:visible}body.mr-vnext-body .mr-live-link:after{content:"";position:absolute;right:-1px;top:-2px;width:5px;height:5px;border-top:1px solid rgba(124,231,194,.5);border-right:1px solid rgba(124,231,194,.5);transform:rotate(45deg)}body.mr-vnext-body .mr-live-chain.is-live .mr-live-node[data-kind="core"]{border-color:rgba(124,231,194,.16);background:rgba(124,231,194,.026)}
body.mr-vnext-body .mr-pressure-field{position:absolute;inset:-7%;pointer-events:none;z-index:7}body.mr-vnext-body .mr-pressure-dot{--i:.15;position:absolute;left:var(--x);top:var(--y);width:9px;height:9px;margin:-4.5px;border-radius:50%;background:rgba(124,231,194,calc(.18 + var(--i)*.7));box-shadow:0 0 calc(5px + 18px*var(--i)) rgba(124,231,194,calc(.04 + var(--i)*.2));transform:scale(calc(.72 + var(--i)*.62));transition:transform .32s var(--ease),background .32s var(--ease),box-shadow .32s var(--ease),opacity .32s var(--ease);opacity:calc(.3 + var(--i)*.7)}body.mr-vnext-body .mr-pressure-dot:after{content:"";position:absolute;inset:-5px;border:1px solid rgba(124,231,194,calc(.035 + var(--i)*.13));border-radius:50%;transform:scale(calc(.8 + var(--i)*.55));transition:transform .32s var(--ease),border-color .32s var(--ease)}body.mr-vnext-body .mr-pressure-dot.hot{background:rgba(227,189,114,calc(.18 + var(--i)*.65));box-shadow:0 0 calc(7px + 20px*var(--i)) rgba(227,189,114,calc(.04 + var(--i)*.18))}body.mr-vnext-body .mr-core-wrap.mr-field-active{filter:drop-shadow(0 0 18px rgba(124,231,194,.08))}
body.mr-vnext-body .mr-mobile-state-strip{display:none}
@keyframes mrChainPulse{0%{transform:translateX(-2px);opacity:.65}100%{transform:none;opacity:1}}
body.mr-vnext-body .mr-live-chain.pulse .mr-live-node{animation:mrChainPulse .32s var(--ease)}
@media(max-width:720px){body.mr-vnext-body .mr-live-chain{grid-template-columns:1fr 12px 1fr 12px 1fr;gap:4px;padding:6px;margin-top:7px;border-radius:13px}body.mr-vnext-body .mr-live-node{padding:7px 6px;border-radius:10px}body.mr-vnext-body .mr-live-node b{font-size:11px}body.mr-vnext-body .mr-live-node span{font-size:6px}body.mr-vnext-body .mr-live-node small{font-size:5.5px;letter-spacing:.1em}body.mr-vnext-body .mr-pressure-field{inset:-10%}body.mr-vnext-body .mr-pressure-dot{width:7px;height:7px;margin:-3.5px}body.mr-vnext-body .mr-mobile-state-strip{position:fixed;z-index:61;left:10px;right:10px;bottom:calc(62px + env(safe-area-inset-bottom));height:45px;display:grid;grid-template-columns:repeat(3,1fr);align-items:center;border:1px solid rgba(208,230,224,.1);border-radius:15px;background:rgba(9,15,16,.86);backdrop-filter:blur(18px);box-shadow:0 16px 46px rgba(0,0,0,.24);overflow:hidden;transform:translateY(0);transition:transform .24s var(--ease),opacity .24s ease}.mr-mobile-state-strip button{appearance:none;border:0;background:transparent;color:inherit;height:100%;padding:5px 7px;min-width:0;position:relative}.mr-mobile-state-strip button+button:before{content:"";position:absolute;left:0;top:10px;bottom:10px;width:1px;background:var(--line)}.mr-mobile-state-strip small{display:block;color:#667974;font-size:5.5px;letter-spacing:.12em}.mr-mobile-state-strip b{display:block;margin-top:3px;font-size:10px;font-weight:560;font-variant-numeric:tabular-nums;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.mr-mobile-state-strip.hidden{transform:translateY(12px);opacity:0;pointer-events:none}body.mr-vnext-body{padding-bottom:112px}}
@media(prefers-reduced-motion:reduce){body.mr-vnext-body .mr-live-node,body.mr-vnext-body .mr-pressure-dot,body.mr-vnext-body .mr-pressure-dot:after,body.mr-vnext-body .mr-mobile-state-strip{transition:none!important}body.mr-vnext-body .mr-live-chain.pulse .mr-live-node{animation:none!important}}
`;
document.head.appendChild(css);

let tries=0;const timer=setInterval(()=>{tries++;if($('#mrPreview')&&$('#mrWorkspace')&&$('#mrFactorLegend')){clearInterval(timer);init()}else if(tries>120)clearInterval(timer)},80);

function init(){
 addLiveChain();
 addPressureField();
 addMobileStateStrip();
 capture('money_resilience_experience_v2_loaded',{motion:reduce?'reduced':'full'});
}
function lang(){return document.documentElement.lang==='en'?'en':'ja'}
function labels(){return lang()==='ja'?{market:'相場',pressure:'圧力',core:'耐久力',score:'SCORE',shock:'SHOCK',runway:'RUNWAY'}:{market:'Market',pressure:'Pressure',core:'Resilience',score:'SCORE',shock:'SHOCK',runway:'RUNWAY'}}
function topFactor(){const arr=$$('#mrFactorLegend .mr-factor').map((el,i)=>({el,i,name:($('span',el)?.textContent||'').trim()||`F${i+1}`,v:clamp(num($('b',el)?.textContent),0,100)})).sort((a,b)=>b.v-a.v);return arr[0]||{name:'—',v:0}}
function pulse(el){if(!el||reduce)return;el.classList.remove('pulse');void el.offsetWidth;el.classList.add('pulse');setTimeout(()=>el.classList.remove('pulse'),360)}

function addLiveChain(){const host=$('#mrPreview .mr-preview-inner')||$('#mrPreview');if(!host||$('.mr-live-chain',host))return;const chain=document.createElement('div');chain.className='mr-live-chain';chain.innerHTML='<div class="mr-live-node" data-kind="market"><small><i></i><em></em></small><b>—</b><span>USD/JPY</span></div><i class="mr-live-link"></i><div class="mr-live-node" data-kind="pressure"><small><i></i><em></em></small><b>—</b><span>0</span></div><i class="mr-live-link"></i><div class="mr-live-node" data-kind="core"><small><i></i><em></em></small><b>—</b><span>/100</span></div>';host.appendChild(chain);
 let prev='';const sync=()=>{const l=labels(),market=$('[data-kind="market"]',chain),pressure=$('[data-kind="pressure"]',chain),core=$('[data-kind="core"]',chain),usd=($('#mrUsd')?.textContent||'—').trim(),delta=($('#mrMarketDelta')?.textContent||'').trim(),f=topFactor(),score=($('[data-core="preview"] [data-core-score]')?.textContent||$('[data-core="main"] [data-core-score]')?.textContent||'—').trim();$('em',market).textContent=l.market;$('b',market).textContent=usd;$('span',market).textContent=delta||'USD/JPY';$('em',pressure).textContent=l.pressure;$('b',pressure).textContent=f.name;$('span',pressure).textContent=Math.round(f.v)+'%';$('em',core).textContent=l.core;$('b',core).textContent=score;$('span',core).textContent='/100';chain.classList.toggle('is-live',usd!=='—'&&score!=='—');const sig=[usd,delta,f.name,f.v,score,lang()].join('|');if(prev&&sig!==prev)pulse(chain);prev=sig};
 ['#mrUsd','#mrMarketDelta','#mrFactorLegend','[data-core="preview"] [data-core-score]','[data-core="main"] [data-core-score]'].forEach(s=>{const el=$(s);if(el)new MutationObserver(()=>requestAnimationFrame(sync)).observe(el,{subtree:true,childList:true,characterData:true,attributes:true})});document.addEventListener('click',e=>{if(e.target.closest('[data-lang]'))setTimeout(sync,30)});sync();}

function addPressureField(){const core=$('.mr-core-card .mr-core-wrap');if(!core||$('.mr-pressure-field',core))return;const field=document.createElement('div');field.className='mr-pressure-field';const pos=[[50,2],[88,25],[90,73],[50,98],[10,73],[12,25]];field.innerHTML=pos.map((p,i)=>`<i class="mr-pressure-dot" data-i="${i}" style="--x:${p[0]}%;--y:${p[1]}%;--i:.1"></i>`).join('');core.appendChild(field);
 const sync=()=>{const factors=$$('#mrFactorLegend .mr-factor').slice(0,6).map((el,i)=>({name:($('span',el)?.textContent||'').trim(),v:clamp(num($('b',el)?.textContent),0,100),i}));const hottest=Math.max(...factors.map(x=>x.v),0);factors.forEach((f,i)=>{const d=$(`[data-i="${i}"]`,field);if(!d)return;const intensity=clamp(f.v/100,.04,1);d.style.setProperty('--i',intensity.toFixed(3));d.classList.toggle('hot',f.v===hottest&&hottest>45);d.title=`${f.name} ${Math.round(f.v)}`});core.classList.toggle('mr-field-active',hottest>20)};new MutationObserver(()=>requestAnimationFrame(sync)).observe($('#mrFactorLegend'),{subtree:true,childList:true,characterData:true,attributes:true});sync();}

function findMetric(regex,fallback){const tiles=$$('#mrResultGrid .mr-result-tile');const hit=tiles.find(t=>regex.test(($('small',t)?.textContent||'').trim()));return ($('b',hit||tiles[fallback])?.textContent||'—').trim()}
function addMobileStateStrip(){if($('.mr-mobile-state-strip'))return;const bar=document.createElement('div');bar.className='mr-mobile-state-strip';bar.innerHTML='<button type="button" data-jump="core"><small></small><b>—</b></button><button type="button" data-jump="result"><small></small><b>—</b></button><button type="button" data-jump="result"><small></small><b>—</b></button>';document.body.appendChild(bar);
 const sync=()=>{const l=labels(),bs=$$('button',bar);$('small',bs[0]).textContent=l.score;$('small',bs[1]).textContent=l.shock;$('small',bs[2]).textContent=l.runway;$('b',bs[0]).textContent=($('[data-core="main"] [data-core-score]')?.textContent||'—').trim();$('b',bs[1]).textContent=findMetric(/shock|月間/i,1);$('b',bs[2]).textContent=findMetric(/runway|現金/i,2)};
 const targets=[$('[data-core="main"] [data-core-score]'),$('#mrResultGrid')].filter(Boolean);targets.forEach(el=>new MutationObserver(()=>requestAnimationFrame(sync)).observe(el,{subtree:true,childList:true,characterData:true,attributes:true}));document.addEventListener('click',e=>{if(e.target.closest('[data-lang]'))setTimeout(sync,30);const b=e.target.closest('.mr-mobile-state-strip button');if(!b)return;const target=b.dataset.jump==='core'?$('.mr-core-card'):$('.mr-result-card');target?.scrollIntoView({behavior:reduce?'auto':'smooth',block:'center'});capture('money_resilience_mobile_state_jump',{target:b.dataset.jump})});
 let lastY=scrollY;addEventListener('scroll',()=>{if(innerWidth>720)return;const y=scrollY,down=y>lastY&&y>180;bar.classList.toggle('hidden',down);lastY=y},{passive:true});sync();}
})();