(function(){
  'use strict';
  if(location.pathname!=='/money-resilience/'&&location.pathname!=='/money-resilience/index.html')return;

  const API='https://api.frankfurter.dev/v2/rates';
  const REFRESH_MS=5*60*1000;
  const CACHE_KEY='mr_market_pulse_ecb_v2';
  const reduceMotion=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const fmt=new Intl.NumberFormat('ja-JP',{minimumFractionDigits:2,maximumFractionDigits:2});
  const fmtPct=new Intl.NumberFormat('ja-JP',{minimumFractionDigits:2,maximumFractionDigits:2,signDisplay:'always'});

  const style=document.createElement('style');
  style.id='mr-v6-style';
  style.textContent=`
    :root{--mr-v6-ink:#172422;--mr-v6-muted:#6d7d79;--mr-v6-line:rgba(23,36,34,.10);--mr-v6-surface:rgba(255,255,255,.78);--mr-v6-radius:22px;--mr-v6-ease:cubic-bezier(.2,.75,.25,1)}
    body{font-weight:400;letter-spacing:-.008em;-webkit-font-smoothing:antialiased;text-rendering:optimizeLegibility}
    .brand{font-weight:650;letter-spacing:-.025em}.brand-copy small{font-weight:550;letter-spacing:.075em}.privacy-pill{font-weight:550;background:rgba(255,255,255,.58);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px)}
    .eyebrow{font-weight:650;letter-spacing:.075em}h1{font-weight:650;letter-spacing:-.052em;line-height:1.01;text-wrap:balance}.hero-lead{font-weight:430;line-height:1.72;color:#52615e}.hero-lead strong{font-weight:620}
    .primary,.secondary,.tool-btn,.module-btn{font-weight:620;letter-spacing:-.01em;box-shadow:none}.primary{box-shadow:0 10px 26px rgba(12,23,24,.12)}.hero-meta{font-weight:540;color:#6b7a77}
    .jumpbar{gap:7px}.jumpbar a{font-weight:560;background:rgba(255,255,255,.52);backdrop-filter:blur(14px);-webkit-backdrop-filter:blur(14px);transition:background .18s var(--mr-v6-ease),border-color .18s var(--mr-v6-ease),transform .18s var(--mr-v6-ease)}.jumpbar a:hover{background:#fff;border-color:rgba(23,36,34,.18);transform:translateY(-1px)}
    .utility-head h2,.modules-head h2{font-weight:620;letter-spacing:-.045em}.utility-head p,.modules-head p{font-weight:430;line-height:1.68}.panel{border-color:var(--mr-v6-line);border-radius:var(--mr-v6-radius);box-shadow:0 14px 40px rgba(23,42,39,.055);background:rgba(255,255,255,.76);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}
    .panel-head strong{font-weight:620}.panel-head small,.scenario-label span{font-weight:480}.scenario-label b{font-weight:610}.scenario button{font-weight:590}.scenario button[aria-pressed="true"]{box-shadow:0 3px 10px rgba(22,44,40,.07)}.assumption b{font-weight:620}.assumption small{font-weight:470}
    .field label{font-weight:600}.field label small{font-weight:420;line-height:1.5}.money-input span,.percent-input span{font-weight:560}.money-input input,.percent-input input{font-weight:590;font-variant-numeric:tabular-nums}.input-foot{font-weight:450}
    .result-top span{font-weight:620}.result-status{font-weight:520!important}.score-value{font-weight:650;font-variant-numeric:tabular-nums}.verdict{font-weight:610}.verdict-copy{font-weight:430;line-height:1.62}.impact-main small,.metric small{font-weight:480}.impact-main b,.metric b{font-weight:610;font-variant-numeric:tabular-nums}.impact-main em,.metric i{font-weight:430}.impact-row{font-weight:520}.priority-box .kicker{font-weight:650}.priority-num{font-weight:650}.priority-item b{font-weight:590}.priority-item small{font-weight:420;line-height:1.52}
    .compare-card{font-weight:400;background:rgba(255,255,255,.56);box-shadow:none}.compare-card small{font-weight:540}.compare-card b{font-weight:610;font-variant-numeric:tabular-nums}.compare-card em{font-weight:430}.module-kicker{font-weight:620}.module h3,.trust-card h3{font-weight:610}.module>p,.trust-card p{font-weight:420;line-height:1.7}.mini-field label{font-weight:540}.mini-field input{font-weight:560;font-variant-numeric:tabular-nums}.provider strong{font-weight:590}.module-result small{font-weight:480}.module-result b{font-weight:620;font-variant-numeric:tabular-nums}.module-result span,.winner,.module-note{font-weight:430}.method summary{font-weight:580}.footer-inner{font-weight:430}

    .signal-card.mr-live{min-height:405px;padding:24px;background:linear-gradient(155deg,#0b1717 0%,#102421 58%,#14332c 100%);border:1px solid rgba(255,255,255,.07);border-radius:26px;color:#f7fbf8;box-shadow:0 24px 64px rgba(12,23,24,.16)}
    .signal-card.mr-live:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 88% 4%,rgba(103,217,173,.18),transparent 35%),linear-gradient(rgba(255,255,255,.018) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.018) 1px,transparent 1px);background-size:auto,32px 32px,32px 32px;pointer-events:none}.signal-card.mr-live:after{content:"";position:absolute;width:220px;height:220px;border-radius:50%;right:-130px;bottom:-150px;background:rgba(103,217,173,.08);filter:blur(10px);pointer-events:none}.mr-market{position:relative;z-index:2;display:flex;flex-direction:column;height:100%;min-height:355px}
    .mr-market-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.mr-market-title{display:flex;align-items:center;gap:9px;font-size:9px;font-weight:600;letter-spacing:.12em;text-transform:uppercase;color:#a8c0b9}.mr-market-dot{width:7px;height:7px;border-radius:50%;background:#67d9ad;box-shadow:0 0 0 4px rgba(103,217,173,.10);animation:mrPulse 2.7s ease-in-out infinite}.mr-market-dot.off{background:#82938f;box-shadow:none;animation:none}
    .mr-refresh{display:inline-grid;place-items:center;width:34px;height:34px;border:1px solid rgba(255,255,255,.09);border-radius:12px;background:rgba(255,255,255,.045);color:#cfe0da;cursor:pointer;transition:transform .18s var(--mr-v6-ease),background .18s var(--mr-v6-ease),border-color .18s var(--mr-v6-ease)}.mr-refresh:hover{background:rgba(255,255,255,.08);border-color:rgba(255,255,255,.14);transform:translateY(-1px)}.mr-refresh:active{transform:scale(.96)}.mr-refresh svg{width:14px;height:14px}.mr-refresh.loading svg{animation:mrSpin .8s linear infinite}
    .mr-primary{display:grid;grid-template-columns:minmax(0,1fr) 142px;gap:20px;align-items:end;margin-top:23px}.mr-pair{font-size:10px;font-weight:560;color:#94aaa4;letter-spacing:.055em}.mr-rate{display:flex;align-items:baseline;gap:8px;margin-top:4px}.mr-rate strong{font-size:clamp(42px,4.7vw,54px);line-height:.96;letter-spacing:-.055em;font-weight:650;font-variant-numeric:tabular-nums}.mr-rate small{font-size:9px;color:#819791;font-weight:500}.mr-delta{display:inline-flex;align-items:center;gap:5px;margin-top:11px;padding:5px 8px;border-radius:999px;background:rgba(103,217,173,.085);color:#8ce6c0;font-size:9px;font-weight:570}.mr-delta.down{background:rgba(231,127,114,.085);color:#eea49a}.mr-delta.flat{background:rgba(255,255,255,.06);color:#bac8c4}.mr-delta svg{width:11px;height:11px}.mr-window{display:block;margin-top:6px;color:#748983;font-size:8.5px;font-weight:430}
    .mr-spark{width:142px;height:88px;overflow:visible}.mr-spark path.line{fill:none;stroke:#67d9ad;stroke-width:2.35;stroke-linecap:round;stroke-linejoin:round;filter:drop-shadow(0 4px 6px rgba(103,217,173,.12))}.mr-spark path.area{fill:url(#mrArea)}.mr-spark .base{stroke:rgba(255,255,255,.065);stroke-width:1;stroke-dasharray:3 4}.mr-spark .end{fill:#67d9ad;stroke:#102522;stroke-width:3}.mr-spark.draw path.line{stroke-dasharray:300;stroke-dashoffset:300;animation:mrDraw .9s var(--mr-v6-ease) forwards}
    .mr-range{display:flex;justify-content:space-between;gap:8px;margin-top:14px;padding-top:13px;border-top:1px solid rgba(255,255,255,.065);color:#7d918b;font-size:8.5px;font-weight:450}.mr-range b{color:#cad9d4;font-weight:570;font-variant-numeric:tabular-nums}.mr-cross{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:17px}.mr-cross-card{padding:12px 13px;border-radius:15px;border:1px solid rgba(255,255,255,.065);background:rgba(255,255,255,.032);transition:transform .18s var(--mr-v6-ease),background .18s var(--mr-v6-ease),border-color .18s var(--mr-v6-ease)}.mr-cross-card:hover{transform:translateY(-2px);background:rgba(255,255,255,.05);border-color:rgba(255,255,255,.09)}.mr-cross-card span{display:block;color:#80968f;font-size:8.5px;font-weight:530;letter-spacing:.055em}.mr-cross-card b{display:block;margin-top:4px;font-size:18px;letter-spacing:-.025em;font-weight:600;font-variant-numeric:tabular-nums}.mr-cross-card small{display:block;margin-top:3px;color:#71867f;font-size:8px;font-weight:400}
    .mr-market-foot{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:auto;padding-top:17px;color:#738781;font-size:8px;font-weight:410}.mr-source{color:#98ada6;text-decoration:none;border-bottom:1px solid rgba(157,178,172,.20)}.mr-source:hover{color:#d6e5e0}.mr-updated{display:flex;align-items:center;gap:6px}.mr-updated:before{content:"";width:5px;height:5px;border-radius:50%;background:#67d9ad}.mr-error{display:grid;place-items:center;min-height:290px;text-align:center;color:#9fb2ac}.mr-error b{display:block;color:#f6faf7;font-size:15px;margin-bottom:5px;font-weight:590}.mr-error button{margin-top:12px;border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.06);color:#fff;border-radius:11px;padding:9px 12px;font-weight:560;cursor:pointer}.mr-skeleton{position:relative;overflow:hidden;background:rgba(255,255,255,.05);border-radius:8px;color:transparent!important}.mr-skeleton:after{content:"";position:absolute;inset:0;transform:translateX(-100%);background:linear-gradient(90deg,transparent,rgba(255,255,255,.07),transparent);animation:mrShimmer 1.3s infinite}.mr-flash{animation:mrFlash .48s var(--mr-v6-ease)}
    .compare-card{cursor:pointer;transition:transform .18s var(--mr-v6-ease),box-shadow .18s var(--mr-v6-ease),border-color .18s var(--mr-v6-ease),background .18s var(--mr-v6-ease)}.compare-card:hover{transform:translateY(-2px);background:rgba(255,255,255,.82)}.compare-card:active{transform:translateY(0) scale(.992)}.compare-card:focus-visible{outline:3px solid rgba(103,217,173,.20);outline-offset:2px}.result-panel.has-result{animation:mrResultIn .38s var(--mr-v6-ease)}.result-panel.mr-result-pulse{box-shadow:0 24px 60px rgba(12,23,24,.16),0 0 0 3px rgba(103,217,173,.065)}.mr-reveal{opacity:0;transform:translateY(12px);transition:opacity .6s var(--mr-v6-ease),transform .6s var(--mr-v6-ease)}.mr-reveal.is-visible{opacity:1;transform:none}
    @keyframes mrPulse{50%{transform:scale(.75);opacity:.55}}@keyframes mrSpin{to{transform:rotate(360deg)}}@keyframes mrDraw{to{stroke-dashoffset:0}}@keyframes mrShimmer{to{transform:translateX(100%)}}@keyframes mrFlash{0%{opacity:.45;transform:translateY(1px)}100%{opacity:1;transform:none}}@keyframes mrResultIn{from{transform:translateY(4px);opacity:.94}to{transform:none;opacity:1}}
    @media(max-width:940px){.hero{gap:26px;padding-bottom:34px}.signal-card.mr-live{max-width:680px;width:100%;justify-self:center}.utility-head,.modules-head{gap:8px}.workspace{gap:13px}.module-grid{gap:13px}}
    @media(max-width:620px){.shell{width:min(100% - 22px,1160px)}.topbar{min-height:58px}.mark{width:34px;height:34px;border-radius:11px}.mark svg{width:20px;height:20px}.hero{padding:19px 0 29px;gap:18px}.eyebrow{font-size:10px;margin-bottom:12px}h1{font-size:clamp(38px,10.8vw,48px);letter-spacing:-.048em;line-height:1.03}.hero-lead{font-size:14px;margin-top:14px;line-height:1.72}.hero-actions{margin-top:18px;gap:8px}.primary,.secondary{min-height:45px;border-radius:13px}.hero-meta{font-size:10px;margin-top:14px;gap:9px}.signal-card.mr-live{min-height:356px;padding:19px;border-radius:23px}.mr-market{min-height:318px}.mr-market-title{font-size:8.2px;letter-spacing:.105em}.mr-refresh{width:32px;height:32px;border-radius:11px}.mr-primary{grid-template-columns:minmax(0,1fr) 104px;gap:10px;margin-top:20px}.mr-spark{width:104px;height:70px}.mr-rate strong{font-size:40px}.mr-rate small{font-size:8px}.mr-pair{font-size:9px}.mr-delta{margin-top:9px;font-size:8.5px}.mr-window{font-size:8px}.mr-range{font-size:8px;margin-top:12px;padding-top:11px}.mr-cross{gap:8px;margin-top:14px}.mr-cross-card{padding:11px;border-radius:13px}.mr-cross-card b{font-size:16px}.mr-market-foot{align-items:flex-start;flex-direction:column;gap:4px;padding-top:13px;font-size:7.6px}.jumpbar{display:flex;flex-wrap:nowrap;overflow-x:auto;padding:0 0 20px;scroll-snap-type:x proximity;scrollbar-width:none;-webkit-overflow-scrolling:touch}.jumpbar::-webkit-scrollbar{display:none}.jumpbar a{flex:0 0 auto;scroll-snap-align:start;padding:8px 11px;font-size:10px}.utility{padding:12px 0 42px}.utility-head h2,.modules-head h2{font-size:30px}.utility-head p,.modules-head p{font-size:12px}.panel{border-radius:19px}.panel-head{padding-top:17px;padding-bottom:17px}.field{border-radius:13px}.result-top{padding-top:18px}.module{padding:17px}.module h3{font-size:19px}.trust-card{padding:19px;border-radius:19px}}
    @media(prefers-reduced-motion:reduce){.mr-market-dot,.mr-spark.draw path.line,.mr-skeleton:after,.mr-flash{animation:none!important}.compare-card,.mr-refresh,.mr-cross-card,.mr-reveal,.jumpbar a{transition:none!important}.mr-reveal{opacity:1!important;transform:none!important}}
  `;
  document.head.appendChild(style);

  function isoDateDaysAgo(days){const d=new Date();d.setDate(d.getDate()-days);return d.toISOString().slice(0,10)}
  function reciprocal(n){return n>0?1/n:0}
  function pctChange(first,last){return first?((last-first)/first)*100:0}
  function arrowIcon(delta){if(Math.abs(delta)<.005)return '<svg viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="M3 8h10" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>';return delta>0?'<svg viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="m4 10 4-4 4 4M8 6v7" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>':'<svg viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="m4 6 4 4 4-4M8 10V3" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>'}
  function linePath(values,w=132,h=84,pad=7){if(values.length<2)return'';const min=Math.min(...values),max=Math.max(...values),range=max-min||1;return values.map((v,i)=>{const x=pad+(i/(values.length-1))*(w-pad*2),y=h-pad-((v-min)/range)*(h-pad*2);return`${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`}).join(' ')}
  function areaPath(values,w=132,h=84,pad=7){if(values.length<2)return'';const line=linePath(values,w,h,pad);return`${line} L${w-pad},${h-pad} L${pad},${h-pad} Z`}
  function safeCacheGet(){try{const x=JSON.parse(sessionStorage.getItem(CACHE_KEY)||'null');return x&&x.payload&&Date.now()-x.savedAt<REFRESH_MS?x.payload:null}catch(_){return null}}
  function safeCacheSet(payload){try{sessionStorage.setItem(CACHE_KEY,JSON.stringify({savedAt:Date.now(),payload}))}catch(_){}}
  function capture(name,props){try{if(window.scosCapture)window.scosCapture(name,props||{})}catch(_){}}

  const card=$('.signal-card');
  if(!card)return;
  card.classList.add('mr-live');
  card.removeAttribute('aria-hidden');
  card.setAttribute('aria-label','最新の為替参考レート');
  card.innerHTML=`<div class="mr-market" id="mrMarket" aria-live="polite"><div class="mr-market-head"><div class="mr-market-title"><span class="mr-market-dot"></span>Market pulse · ECB reference</div><button class="mr-refresh" type="button" aria-label="為替データを更新" title="更新"><svg viewBox="0 0 24 24" fill="none"><path d="M20 6v5h-5M4 18v-5h5M6.2 9a7 7 0 0 1 11.7-2.1L20 11M4 13l2.1 4.1A7 7 0 0 0 18 15" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg></button></div><div class="mr-primary"><div><div class="mr-pair">USD / JPY</div><div class="mr-rate"><strong id="mrUsd" class="mr-skeleton">000.00</strong><small>JPY</small></div><div class="mr-delta flat" id="mrDelta"><span>30日</span></div><span class="mr-window" id="mrDate">最新参考レートを取得中</span></div><svg class="mr-spark" id="mrSpark" viewBox="0 0 132 84" role="img" aria-label="USD JPY 30日推移"><defs><linearGradient id="mrArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#67d9ad" stop-opacity=".22"/><stop offset="1" stop-color="#67d9ad" stop-opacity="0"/></linearGradient></defs><path class="base" d="M7 72H125"/><path class="area" id="mrAreaPath" d=""/><path class="line" id="mrLinePath" d=""/><circle class="end" id="mrEnd" cx="0" cy="0" r="4" opacity="0"/></svg></div><div class="mr-range"><span>30日 LOW <b id="mrLow">—</b></span><span>30日 HIGH <b id="mrHigh">—</b></span></div><div class="mr-cross"><div class="mr-cross-card"><span>EUR / JPY</span><b id="mrEur" class="mr-skeleton">000.00</b><small>参考レート</small></div><div class="mr-cross-card"><span>GBP / JPY</span><b id="mrGbp" class="mr-skeleton">000.00</b><small>参考レート</small></div></div><div class="mr-market-foot"><span class="mr-updated" id="mrUpdated">ブラウザから最新値を取得</span><span>取引レートではありません · <a class="mr-source" href="https://frankfurter.dev/providers/ecb/" target="_blank" rel="noopener noreferrer">Data: ECB via Frankfurter</a></span></div></div>`;

  function plot(values){const svg=$('#mrSpark'),line=$('#mrLinePath'),area=$('#mrAreaPath'),end=$('#mrEnd');if(values.length<2)return;line.setAttribute('d',linePath(values));area.setAttribute('d',areaPath(values));const min=Math.min(...values),max=Math.max(...values),range=max-min||1,w=132,h=84,pad=7,v=values[values.length-1],x=w-pad,y=h-pad-((v-min)/range)*(h-pad*2);end.setAttribute('cx',x);end.setAttribute('cy',y);end.setAttribute('opacity','1');svg.classList.remove('draw');if(!reduceMotion)requestAnimationFrame(()=>svg.classList.add('draw'))}
  function flash(selector){const node=$(selector);if(!node||reduceMotion)return;node.classList.remove('mr-flash');void node.offsetWidth;node.classList.add('mr-flash')}
  function render(data){const rates=Object.fromEntries(data.latest.map(x=>[x.quote,reciprocal(x.rate)]));const history=data.history.map(x=>({date:x.date,value:reciprocal(x.rate)})).filter(x=>x.value>0).sort((a,b)=>a.date.localeCompare(b.date));const values=history.map(x=>x.value);if(!rates.USD||!rates.EUR||!rates.GBP||values.length<2)throw new Error('Incomplete market data');const delta=pctChange(values[0],values[values.length-1]);$('#mrUsd').textContent=fmt.format(rates.USD);$('#mrEur').textContent=fmt.format(rates.EUR);$('#mrGbp').textContent=fmt.format(rates.GBP);['#mrUsd','#mrEur','#mrGbp'].forEach(s=>$(s).classList.remove('mr-skeleton'));const deltaEl=$('#mrDelta');deltaEl.className='mr-delta '+(delta>.005?'up':delta<-.005?'down':'flat');deltaEl.innerHTML=arrowIcon(delta)+`30日 ${fmtPct.format(delta)}%`;const date=(data.latest[0]&&data.latest[0].date)||history[history.length-1].date;$('#mrDate').textContent=`${date} 参考レート`;$('#mrLow').textContent=fmt.format(Math.min(...values));$('#mrHigh').textContent=fmt.format(Math.max(...values));$('#mrUpdated').textContent=`取得 ${new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})} · 5分ごとに再確認`;plot(values);flash('#mrUsd');card.dataset.marketState='ready'}
  function renderError(){const cached=safeCacheGet();if(cached){try{render(cached);$('#mrUpdated').textContent='一時的に更新できません · 直近取得値を表示';$('.mr-market-dot').classList.add('off');return}catch(_){}}card.innerHTML='<div class="mr-error"><div><b>為替データを取得できませんでした。</b><span>診断機能はそのまま利用できます。</span><br><button type="button" id="mrRetry">もう一度取得</button></div></div>';$('#mrRetry').addEventListener('click',()=>load(true))}
  async function load(force){const refresh=$('.mr-refresh');if(refresh)refresh.classList.add('loading');try{if(!force){const cached=safeCacheGet();if(cached){render(cached);return}}const from=isoDateDaysAgo(38);const latestUrl=`${API}?base=JPY&quotes=USD,EUR,GBP&providers=ECB`;const historyUrl=`${API}?base=JPY&quotes=USD&from=${from}&providers=ECB`;const [a,b]=await Promise.all([fetch(latestUrl,{cache:'no-store'}),fetch(historyUrl,{cache:'no-store'})]);if(!a.ok||!b.ok)throw new Error('Market API unavailable');const payload={latest:await a.json(),history:await b.json()};safeCacheSet(payload);render(payload);capture('money_resilience_market_pulse_loaded',{provider:'ECB_via_Frankfurter'});}catch(e){renderError();capture('money_resilience_market_pulse_error',{provider:'ECB_via_Frankfurter'});}finally{const r=$('.mr-refresh');if(r)r.classList.remove('loading')}}

  $('.mr-refresh').addEventListener('click',()=>{capture('money_resilience_market_refresh');load(true)});load(false);setInterval(()=>load(true),REFRESH_MS);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')load(false)});
  const compareCards=$$('#scenarioCompare .compare-card');const scenarioButtons=$$('[data-scenario]');compareCards.forEach((c,i)=>{c.tabIndex=0;c.setAttribute('role','button');c.setAttribute('aria-label',`${['軽度','標準','強め'][i]}シナリオを選択`);const activate=()=>scenarioButtons[i]&&scenarioButtons[i].click();c.addEventListener('click',activate);c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate()}})});
  const result=$('#resultPanel');if(result){let pulseTimer;const observer=new MutationObserver(()=>{if(!result.classList.contains('has-result'))return;result.classList.add('mr-result-pulse');clearTimeout(pulseTimer);pulseTimer=setTimeout(()=>result.classList.remove('mr-result-pulse'),260)});observer.observe(result,{subtree:true,childList:true,characterData:true});}
  if(!reduceMotion&&'IntersectionObserver'in window){const revealTargets=$$('.utility-head,.workspace,#scenarioCompare,.modules-head,.module,.trust-card');revealTargets.forEach(el=>el.classList.add('mr-reveal'));const revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}})},{rootMargin:'0px 0px -8% 0px',threshold:.08});revealTargets.forEach(el=>revealObserver.observe(el));}
})();