(function(){
  'use strict';
  if(location.pathname!=='/money-resilience/'&&location.pathname!=='/money-resilience/index.html')return;

  const API='https://api.frankfurter.dev/v2/rates';
  const REFRESH_MS=5*60*1000;
  const CACHE_KEY='mr_market_pulse_ecb_v1';
  const reduceMotion=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const fmt=new Intl.NumberFormat('ja-JP',{minimumFractionDigits:2,maximumFractionDigits:2});
  const fmtPct=new Intl.NumberFormat('ja-JP',{minimumFractionDigits:2,maximumFractionDigits:2,signDisplay:'always'});

  const style=document.createElement('style');
  style.textContent=`
    .signal-card.mr-live{min-height:420px;background:linear-gradient(152deg,#0c1718 0%,#102522 56%,#16342d 100%);border-color:rgba(255,255,255,.08);color:#f7fbf8;box-shadow:0 34px 86px rgba(12,23,24,.24)}
    .signal-card.mr-live:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 86% 4%,rgba(103,217,173,.22),transparent 34%),linear-gradient(rgba(255,255,255,.025) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.025) 1px,transparent 1px);background-size:auto,30px 30px,30px 30px;pointer-events:none}
    .mr-market{position:relative;z-index:2;display:flex;flex-direction:column;height:100%;min-height:368px}
    .mr-market-head{display:flex;align-items:center;justify-content:space-between;gap:12px}.mr-market-title{display:flex;align-items:center;gap:9px;font-size:10px;font-weight:900;letter-spacing:.11em;text-transform:uppercase;color:#bad2cb}.mr-market-dot{width:8px;height:8px;border-radius:50%;background:#67d9ad;box-shadow:0 0 0 5px rgba(103,217,173,.11);animation:mrPulse 2.4s ease-in-out infinite}.mr-market-dot.off{background:#82938f;box-shadow:none;animation:none}.mr-refresh{display:inline-grid;place-items:center;width:34px;height:34px;border:1px solid rgba(255,255,255,.1);border-radius:11px;background:rgba(255,255,255,.06);color:#d6e5e0;cursor:pointer;transition:.18s ease}.mr-refresh:hover{background:rgba(255,255,255,.11);transform:translateY(-1px)}.mr-refresh svg{width:15px;height:15px}.mr-refresh.loading svg{animation:mrSpin .8s linear infinite}
    .mr-primary{display:grid;grid-template-columns:minmax(0,1fr) 132px;gap:16px;align-items:end;margin-top:24px}.mr-pair{font-size:11px;font-weight:850;color:#8ea8a0;letter-spacing:.05em}.mr-rate{display:flex;align-items:baseline;gap:8px;margin-top:3px}.mr-rate strong{font-size:clamp(38px,4.5vw,55px);line-height:.95;letter-spacing:-.06em;font-weight:900}.mr-rate small{font-size:10px;color:#8fa8a0;font-weight:800}.mr-delta{display:inline-flex;align-items:center;gap:5px;margin-top:10px;padding:5px 8px;border-radius:999px;background:rgba(103,217,173,.1);color:#8ce6c0;font-size:10px;font-weight:900}.mr-delta.down{background:rgba(231,127,114,.1);color:#efaa9f}.mr-delta.flat{background:rgba(255,255,255,.07);color:#bac8c4}.mr-delta svg{width:12px;height:12px}.mr-window{display:block;margin-top:5px;color:#748c85;font-size:9px;font-weight:750}
    .mr-spark{width:132px;height:84px;overflow:visible}.mr-spark path.line{fill:none;stroke:#67d9ad;stroke-width:3;stroke-linecap:round;stroke-linejoin:round;filter:drop-shadow(0 6px 8px rgba(103,217,173,.17))}.mr-spark path.area{fill:url(#mrArea)}.mr-spark .base{stroke:rgba(255,255,255,.08);stroke-width:1;stroke-dasharray:3 4}.mr-spark .end{fill:#67d9ad;stroke:#102522;stroke-width:4}.mr-spark.draw path.line{stroke-dasharray:300;stroke-dashoffset:300;animation:mrDraw 1s cubic-bezier(.2,.75,.25,1) forwards}
    .mr-range{display:flex;justify-content:space-between;gap:8px;margin-top:13px;padding-top:13px;border-top:1px solid rgba(255,255,255,.08);color:#879d96;font-size:9px;font-weight:750}.mr-range b{color:#d9e6e2;font-weight:900}
    .mr-cross{display:grid;grid-template-columns:repeat(2,1fr);gap:9px;margin-top:18px}.mr-cross-card{padding:12px 13px;border-radius:14px;border:1px solid rgba(255,255,255,.075);background:rgba(255,255,255,.045);transition:transform .2s ease,background .2s ease}.mr-cross-card:hover{transform:translateY(-2px);background:rgba(255,255,255,.07)}.mr-cross-card span{display:block;color:#819a92;font-size:9px;font-weight:850;letter-spacing:.05em}.mr-cross-card b{display:block;margin-top:3px;font-size:18px;letter-spacing:-.035em}.mr-cross-card small{display:block;margin-top:2px;color:#7f958e;font-size:8px;font-weight:700}
    .mr-market-foot{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:auto;padding-top:18px;color:#789089;font-size:8.5px;font-weight:700}.mr-source{color:#9db2ac;text-decoration:none;border-bottom:1px solid rgba(157,178,172,.25)}.mr-source:hover{color:#d6e5e0}.mr-updated{display:flex;align-items:center;gap:6px}.mr-updated:before{content:"";width:5px;height:5px;border-radius:50%;background:#67d9ad}.mr-error{display:grid;place-items:center;min-height:300px;text-align:center;color:#9fb2ac}.mr-error b{display:block;color:#f6faf7;font-size:16px;margin-bottom:5px}.mr-error button{margin-top:12px;border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.07);color:#fff;border-radius:11px;padding:9px 12px;font-weight:850;cursor:pointer}
    .mr-skeleton{position:relative;overflow:hidden;background:rgba(255,255,255,.06);border-radius:8px;color:transparent!important}.mr-skeleton:after{content:"";position:absolute;inset:0;transform:translateX(-100%);background:linear-gradient(90deg,transparent,rgba(255,255,255,.08),transparent);animation:mrShimmer 1.25s infinite}
    .compare-card{cursor:pointer;transition:transform .18s cubic-bezier(.2,.75,.25,1),box-shadow .18s,border-color .18s}.compare-card:hover{transform:translateY(-2px)}.compare-card:focus-visible{outline:3px solid rgba(103,217,173,.25);outline-offset:2px}.result-panel.has-result{animation:mrResultIn .42s cubic-bezier(.2,.75,.25,1)}.result-panel.mr-result-pulse{box-shadow:0 30px 70px rgba(12,23,24,.19),0 0 0 4px rgba(103,217,173,.08)}
    @keyframes mrPulse{50%{transform:scale(.72);opacity:.55}}@keyframes mrSpin{to{transform:rotate(360deg)}}@keyframes mrDraw{to{stroke-dashoffset:0}}@keyframes mrShimmer{to{transform:translateX(100%)}}@keyframes mrResultIn{from{transform:translateY(5px);opacity:.92}to{transform:none;opacity:1}}
    @media(max-width:620px){.signal-card.mr-live{min-height:390px}.mr-market{min-height:350px}.mr-primary{grid-template-columns:1fr 110px}.mr-spark{width:110px;height:74px}.mr-rate strong{font-size:41px}.mr-cross-card b{font-size:16px}.mr-market-foot{align-items:flex-start;flex-direction:column;gap:5px}}
    @media(prefers-reduced-motion:reduce){.mr-market-dot,.mr-spark.draw path.line,.mr-skeleton:after{animation:none!important}.compare-card,.mr-refresh,.mr-cross-card{transition:none!important}}
  `;
  document.head.appendChild(style);

  function isoDateDaysAgo(days){const d=new Date();d.setDate(d.getDate()-days);return d.toISOString().slice(0,10)}
  function reciprocal(n){return n>0?1/n:0}
  function pctChange(first,last){return first?((last-first)/first)*100:0}
  function arrowIcon(delta){if(Math.abs(delta)<.005)return '<svg viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="M3 8h10" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"/></svg>';return delta>0?'<svg viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="m4 10 4-4 4 4M8 6v7" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>':'<svg viewBox="0 0 16 16" fill="none" aria-hidden="true"><path d="m4 6 4 4 4-4M8 10V3" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>'}
  function linePath(values,w=132,h=84,pad=7){if(values.length<2)return'';const min=Math.min(...values),max=Math.max(...values),range=max-min||1;return values.map((v,i)=>{const x=pad+(i/(values.length-1))*(w-pad*2),y=h-pad-((v-min)/range)*(h-pad*2);return`${i?'L':'M'}${x.toFixed(1)},${y.toFixed(1)}`}).join(' ')}
  function areaPath(values,w=132,h=84,pad=7){if(values.length<2)return'';const line=linePath(values,w,h,pad);return`${line} L${w-pad},${h-pad} L${pad},${h-pad} Z`}
  function safeCacheGet(){try{const x=JSON.parse(sessionStorage.getItem(CACHE_KEY)||'null');return x&&x.payload&&Date.now()-x.savedAt<REFRESH_MS?x.payload:null}catch(_){return null}}
  function safeCacheSet(payload){try{sessionStorage.setItem(CACHE_KEY,JSON.stringify({savedAt:Date.now(),payload}))}catch(_){}}
  function capture(name,props){try{if(window.scosCapture)window.scosCapture(name,props||{})}catch(_){}}

  const card=$('.signal-card');
  if(!card)return;
  card.classList.add('mr-live');
  card.removeAttribute('aria-hidden');
  card.setAttribute('aria-label','最新の為替参考レート');
  card.innerHTML=`<div class="mr-market" id="mrMarket" aria-live="polite"><div class="mr-market-head"><div class="mr-market-title"><span class="mr-market-dot"></span>Market pulse · ECB reference</div><button class="mr-refresh" type="button" aria-label="為替データを更新" title="更新"><svg viewBox="0 0 24 24" fill="none"><path d="M20 6v5h-5M4 18v-5h5M6.2 9a7 7 0 0 1 11.7-2.1L20 11M4 13l2.1 4.1A7 7 0 0 0 18 15" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg></button></div><div class="mr-primary"><div><div class="mr-pair">USD / JPY</div><div class="mr-rate"><strong id="mrUsd" class="mr-skeleton">000.00</strong><small>JPY</small></div><div class="mr-delta flat" id="mrDelta"><span>30日</span></div><span class="mr-window" id="mrDate">最新参考レートを取得中</span></div><svg class="mr-spark" id="mrSpark" viewBox="0 0 132 84" role="img" aria-label="USD JPY 30日推移"><defs><linearGradient id="mrArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#67d9ad" stop-opacity=".25"/><stop offset="1" stop-color="#67d9ad" stop-opacity="0"/></linearGradient></defs><path class="base" d="M7 72H125"/><path class="area" id="mrAreaPath" d=""/><path class="line" id="mrLinePath" d=""/><circle class="end" id="mrEnd" cx="0" cy="0" r="4" opacity="0"/></svg></div><div class="mr-range"><span>30日 LOW <b id="mrLow">—</b></span><span>30日 HIGH <b id="mrHigh">—</b></span></div><div class="mr-cross"><div class="mr-cross-card"><span>EUR / JPY</span><b id="mrEur" class="mr-skeleton">000.00</b><small>参考レート</small></div><div class="mr-cross-card"><span>GBP / JPY</span><b id="mrGbp" class="mr-skeleton">000.00</b><small>参考レート</small></div></div><div class="mr-market-foot"><span class="mr-updated" id="mrUpdated">ブラウザから最新値を取得</span><span>取引レートではありません · <a class="mr-source" href="https://frankfurter.dev/providers/ecb/" target="_blank" rel="noopener noreferrer">Data: ECB via Frankfurter</a></span></div></div>`;

  function plot(values){const svg=$('#mrSpark'),line=$('#mrLinePath'),area=$('#mrAreaPath'),end=$('#mrEnd');if(values.length<2)return;line.setAttribute('d',linePath(values));area.setAttribute('d',areaPath(values));const min=Math.min(...values),max=Math.max(...values),range=max-min||1,w=132,h=84,pad=7,v=values[values.length-1],x=w-pad,y=h-pad-((v-min)/range)*(h-pad*2);end.setAttribute('cx',x);end.setAttribute('cy',y);end.setAttribute('opacity','1');svg.classList.remove('draw');if(!reduceMotion)requestAnimationFrame(()=>svg.classList.add('draw'))}
  function render(data){const rates=Object.fromEntries(data.latest.map(x=>[x.quote,reciprocal(x.rate)]));const history=data.history.map(x=>({date:x.date,value:reciprocal(x.rate)})).filter(x=>x.value>0).sort((a,b)=>a.date.localeCompare(b.date));const values=history.map(x=>x.value);if(!rates.USD||!rates.EUR||!rates.GBP||values.length<2)throw new Error('Incomplete market data');const delta=pctChange(values[0],values[values.length-1]);$('#mrUsd').textContent=fmt.format(rates.USD);$('#mrEur').textContent=fmt.format(rates.EUR);$('#mrGbp').textContent=fmt.format(rates.GBP);['#mrUsd','#mrEur','#mrGbp'].forEach(s=>$(s).classList.remove('mr-skeleton'));const deltaEl=$('#mrDelta');deltaEl.className='mr-delta '+(delta>.005?'up':delta<-.005?'down':'flat');deltaEl.innerHTML=arrowIcon(delta)+`30日 ${fmtPct.format(delta)}%`;const date=(data.latest[0]&&data.latest[0].date)||history[history.length-1].date;$('#mrDate').textContent=`${date} 参考レート`;$('#mrLow').textContent=fmt.format(Math.min(...values));$('#mrHigh').textContent=fmt.format(Math.max(...values));$('#mrUpdated').textContent=`取得 ${new Date().toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})} · 5分ごとに再確認`;plot(values);card.dataset.marketState='ready'}
  function renderError(){const cached=safeCacheGet();if(cached){try{render(cached);$('#mrUpdated').textContent='一時的に更新できません · 直近取得値を表示';$('.mr-market-dot').classList.add('off');return}catch(_){}}card.innerHTML='<div class="mr-error"><div><b>為替データを取得できませんでした。</b><span>診断機能はそのまま利用できます。</span><br><button type="button" id="mrRetry">もう一度取得</button></div></div>';$('#mrRetry').addEventListener('click',load)}
  async function load(force){const refresh=$('.mr-refresh');if(refresh)refresh.classList.add('loading');try{if(!force){const cached=safeCacheGet();if(cached){render(cached);return}}const from=isoDateDaysAgo(38);const latestUrl=`${API}?base=JPY&quotes=USD,EUR,GBP&providers=ECB`;const historyUrl=`${API}?base=JPY&quotes=USD&from=${from}&providers=ECB`;const [a,b]=await Promise.all([fetch(latestUrl,{cache:'no-store'}),fetch(historyUrl,{cache:'no-store'})]);if(!a.ok||!b.ok)throw new Error('Market API unavailable');const payload={latest:await a.json(),history:await b.json()};safeCacheSet(payload);render(payload);capture('money_resilience_market_pulse_loaded',{provider:'ECB_via_Frankfurter'});}catch(e){renderError();capture('money_resilience_market_pulse_error',{provider:'ECB_via_Frankfurter'});}finally{const r=$('.mr-refresh');if(r)r.classList.remove('loading')}}

  $('.mr-refresh').addEventListener('click',()=>{capture('money_resilience_market_refresh');load(true)});
  load(false);
  setInterval(()=>load(true),REFRESH_MS);
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')load(false)});

  const compareCards=$$('#scenarioCompare .compare-card');
  const scenarioButtons=$$('[data-scenario]');
  compareCards.forEach((c,i)=>{c.tabIndex=0;c.setAttribute('role','button');c.setAttribute('aria-label',`${['軽度','標準','強め'][i]}シナリオを選択`);const activate=()=>scenarioButtons[i]&&scenarioButtons[i].click();c.addEventListener('click',activate);c.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();activate()}})});

  const result=$('#resultPanel');
  if(result){let pulseTimer;const observer=new MutationObserver(()=>{if(!result.classList.contains('has-result'))return;result.classList.add('mr-result-pulse');clearTimeout(pulseTimer);pulseTimer=setTimeout(()=>result.classList.remove('mr-result-pulse'),260)});observer.observe(result,{subtree:true,childList:true,characterData:true});}
})();
