(()=>{'use strict';
const path=location.pathname.replace(/index\.html$/,'');
if(path!=='/money-resilience/'&&path!=='/money-resilience')return;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const reduce=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const capture=(name,props={})=>{try{window.scosCapture?.(name,props)}catch(_){}};

const style=document.createElement('style');style.id='mr-site-power-style';style.textContent=`
body.mr-vnext-body .mr-dock{isolation:isolate;overflow:hidden}body.mr-vnext-body .mr-dock>button{position:relative;z-index:2}body.mr-vnext-body .mr-dock-glider{position:absolute;z-index:1;top:6px;bottom:6px;left:0;width:0;border:1px solid rgba(124,231,194,.16);border-radius:13px;background:linear-gradient(135deg,rgba(124,231,194,.14),rgba(125,184,233,.045));box-shadow:inset 0 0 28px rgba(124,231,194,.035),0 10px 32px rgba(0,0,0,.14);pointer-events:none;transition:transform .34s var(--ease),width .34s var(--ease),opacity .2s ease;opacity:0}body.mr-vnext-body .mr-dock-glider.ready{opacity:1}body.mr-vnext-body .mr-dock button.active{background:transparent;box-shadow:none}
body.mr-vnext-body .mr-shock-wrap{padding-top:20px}body.mr-vnext-body .mr-dial-float{position:absolute;top:0;left:0;transform:translateX(0);height:20px;padding:0 8px;border:1px solid rgba(124,231,194,.18);border-radius:999px;background:rgba(11,18,19,.88);backdrop-filter:blur(10px);display:flex;align-items:center;gap:5px;color:#cde5dc;font-size:7px;letter-spacing:.07em;white-space:nowrap;pointer-events:none;box-shadow:0 7px 20px rgba(0,0,0,.16);transition:left .3s var(--ease),transform .3s var(--ease)}body.mr-vnext-body .mr-dial-float i{width:4px;height:4px;border-radius:50%;background:var(--mint);box-shadow:0 0 0 4px rgba(124,231,194,.06)}
body.mr-vnext-body .mr-cause-layer{position:fixed;inset:0;width:100vw;height:100vh;z-index:75;pointer-events:none;overflow:visible}body.mr-vnext-body .mr-cause-layer path{fill:none;stroke:url(#mrCauseGradient);stroke-width:1.45;stroke-linecap:round;filter:drop-shadow(0 0 7px rgba(124,231,194,.25));opacity:0}body.mr-vnext-body .mr-cause-layer circle{fill:var(--mint);filter:drop-shadow(0 0 7px rgba(124,231,194,.65));opacity:0}body.mr-vnext-body .mr-cause-hit{animation:mrCauseHit .52s var(--ease)}body.mr-vnext-body .mr-result-hit{animation:mrResultHit .48s var(--ease)}
body.mr-vnext-body .mr-action.mr-share{color:#cde6dd;border-color:rgba(124,231,194,.18);background:linear-gradient(135deg,rgba(124,231,194,.07),rgba(255,255,255,.014))}body.mr-vnext-body .mr-action.mr-share svg{color:var(--mint)}
body.mr-vnext-body .mr-drawer-foot .mr-utility-bridge{margin-top:12px;display:flex;align-items:center;justify-content:space-between;gap:10px;min-height:36px;padding:0 10px;border:1px solid var(--line);border-radius:11px;color:#9fc8ba;text-decoration:none;font-size:8px;background:rgba(124,231,194,.025)}body.mr-vnext-body .mr-drawer-foot .mr-utility-bridge b{margin:0;font-size:8px;font-weight:560;color:#dbece6}body[data-ruv3="money"] #ruv3-money-snapshot{display:none!important}
@keyframes mrCauseHit{0%{filter:drop-shadow(0 0 0 rgba(124,231,194,0))}45%{filter:drop-shadow(0 0 18px rgba(124,231,194,.35))}100%{filter:none}}@keyframes mrResultHit{0%{box-shadow:0 18px 52px rgba(0,0,0,.14)}45%{box-shadow:0 18px 52px rgba(0,0,0,.14),0 0 0 1px rgba(124,231,194,.22),0 0 34px rgba(124,231,194,.08)}100%{box-shadow:0 18px 52px rgba(0,0,0,.14)}}
@media(max-width:720px){body.mr-vnext-body .mr-dock-glider{display:none}body.mr-vnext-body .mr-shock-wrap{padding-top:18px}body.mr-vnext-body .mr-result-actions{display:grid;grid-template-columns:repeat(4,1fr)}body.mr-vnext-body .mr-action{min-width:0;padding:0 4px}body.mr-vnext-body .mr-action span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}}
@media(prefers-reduced-motion:reduce){body.mr-vnext-body .mr-dock-glider,body.mr-vnext-body .mr-dial-float{transition:none!important}body.mr-vnext-body .mr-cause-hit,body.mr-vnext-body .mr-result-hit{animation:none!important}}
`;
document.head.appendChild(style);

let tries=0;const boot=setInterval(()=>{tries++;if($('#mrWorkspace')&&$('.mr-dock')&&$('#mrResultGrid')){clearInterval(boot);init()}else if(tries>100)clearInterval(boot)},80);

function init(){
 const dock=$('.mr-dock');
 if(dock&&!$('.mr-dock-glider',dock)){const g=document.createElement('i');g.className='mr-dock-glider';dock.prepend(g);const sync=()=>{const a=$('button.active',dock),r=dock.getBoundingClientRect(),b=a?.getBoundingClientRect();if(!a||!b)return;g.style.width=b.width+'px';g.style.transform=`translateX(${b.left-r.left}px)`;requestAnimationFrame(()=>g.classList.add('ready'))};new MutationObserver(sync).observe(dock,{subtree:true,attributes:true,attributeFilter:['class']});window.addEventListener('resize',sync,{passive:true});dock.addEventListener('click',()=>requestAnimationFrame(sync));sync()}

 enhanceStressDial();
 addShareAction();
 addUtilityBridge();
 installCauseLayer();
 watchMarketPulse();
 capture('money_resilience_site_power_loaded',{version:'2026-09-14'});
}

function currentLang(){return document.documentElement.lang==='en'?'en':'ja'}
function enhanceStressDial(){const wrap=$('.mr-shock-wrap'),slider=$('#mrScenario');if(!wrap||!slider||$('.mr-dial-float',wrap))return;const f=document.createElement('div');f.className='mr-dial-float';f.innerHTML='<i></i><span></span>';wrap.appendChild(f);const sync=()=>{const v=Math.max(0,Math.min(2,Number(slider.value)||0)),active=$('.mr-dial-labels button.active'),label=active?.textContent||(['軽度','標準','強め'][v]);$('span',f).textContent=label;f.style.left=(v*50)+'%';f.style.transform=`translateX(${v===0?'0':v===1?'-50%':'-100%'})`};slider.addEventListener('input',sync);document.addEventListener('click',e=>{if(e.target.closest('[data-dial],[data-lang]'))requestAnimationFrame(sync)});sync()}

function shareIcon(){return '<svg viewBox="0 0 24 24"><path d="M12 16V4m0 0L8 8m4-4 4 4"/><path d="M5 12v6a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2v-6"/></svg>'}
function addShareAction(){const actions=$('.mr-result-actions');if(!actions||$('.mr-share',actions))return;const b=document.createElement('button');b.type='button';b.className='mr-action mr-share';b.innerHTML=shareIcon()+'<span>Share</span>';actions.appendChild(b);b.addEventListener('click',async()=>{const raw=Number(($('[data-core="main"] [data-core-score]')?.textContent||'').replace(/[^0-9]/g,''));const band=raw>=80?'80–100':raw>=60?'60–79':raw>=40?'40–59':'0–39';const scenario=$('.mr-dial-labels button.active')?.textContent||'Current';const ja=currentLang()==='ja';const text=ja?`Money Resilience ${band} / ${scenario}\n市場変化への耐久力を確認`:`Money Resilience ${band} / ${scenario}\nCheck your resilience to market change`;const data={title:'Money Resilience Utility',text,url:location.origin+'/money-resilience/'};try{if(navigator.share){await navigator.share(data);capture('money_resilience_result_share',{method:'web_share',score_band:band})}else{await navigator.clipboard.writeText(`${text}\n${data.url}`);capture('money_resilience_result_share',{method:'clipboard',score_band:band});const toast=$('#mrToast');if(toast){toast.textContent=ja?'共有用リンクをコピー':'Share link copied';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1400)}}}catch(_){}})}

function addUtilityBridge(){const foot=$('.mr-drawer-foot');if(!foot||$('.mr-utility-bridge',foot))return;const a=document.createElement('a');a.className='mr-utility-bridge';a.href='/72-hour-household-readiness/?utm_source=money_resilience&utm_medium=utility_bridge&utm_campaign=resilience';a.innerHTML='<span>72H HOME</span><b>生活耐久力 →</b>';a.addEventListener('click',()=>capture('resilience_bridge_click',{from:'money',to:'home',placement:'drawer'}));foot.appendChild(a)}

let causeSvg,causePath,causeDot,causeToken=0;
function installCauseLayer(){causeSvg=document.createElementNS('http://www.w3.org/2000/svg','svg');causeSvg.classList.add('mr-cause-layer');causeSvg.innerHTML='<defs><linearGradient id="mrCauseGradient" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#7db8e9" stop-opacity=".18"/><stop offset=".55" stop-color="#7ce7c2" stop-opacity=".88"/><stop offset="1" stop-color="#7ce7c2" stop-opacity=".15"/></linearGradient></defs><path/><circle r="3"/>';document.body.appendChild(causeSvg);causePath=$('path',causeSvg);causeDot=$('circle',causeSvg);document.addEventListener('input',e=>{const source=e.target.closest('.mr-control,.mr-stress');if(!source)return;const core=$('.mr-core-card .mr-core-wrap');if(!core)return;runCause(source,core);pulse($('.mr-core-card'),'mr-cause-hit');setTimeout(()=>{const result=$('.mr-result-card');if(result){runCause(core,result);pulse(result,'mr-result-hit')}},190)})}
function visibleRect(el){const r=el.getBoundingClientRect();return r.width&&r.height&&r.bottom>0&&r.top<innerHeight&&r.right>0&&r.left<innerWidth?r:null}
function runCause(fromEl,toEl){if(reduce||!causeSvg)return;const a=visibleRect(fromEl),b=visibleRect(toEl);if(!a||!b)return;const token=++causeToken,w=innerWidth,h=innerHeight;causeSvg.setAttribute('viewBox',`0 0 ${w} ${h}`);const x1=a.left+a.width*.82,y1=a.top+a.height*.5,x2=b.left+b.width*.18,y2=b.top+b.height*.5,dx=Math.max(56,Math.abs(x2-x1)*.42);causePath.setAttribute('d',`M${x1},${y1} C${x1+dx},${y1} ${x2-dx},${y2} ${x2},${y2}`);const len=causePath.getTotalLength();causePath.style.opacity='1';causePath.style.strokeDasharray=String(len);causePath.style.strokeDashoffset=String(len);causeDot.style.opacity='1';const start=performance.now(),dur=520;function frame(now){if(token!==causeToken)return;const t=Math.min(1,(now-start)/dur),e=1-Math.pow(1-t,3),p=causePath.getPointAtLength(len*e);causePath.style.strokeDashoffset=String(len*(1-e));causeDot.setAttribute('cx',p.x);causeDot.setAttribute('cy',p.y);causeDot.style.opacity=String(t<.82?1:(1-t)/.18);if(t<1)requestAnimationFrame(frame);else{causePath.style.opacity='0';causeDot.style.opacity='0'}}requestAnimationFrame(frame)}
function pulse(el,cls){if(!el||reduce)return;el.classList.remove(cls);void el.offsetWidth;el.classList.add(cls);setTimeout(()=>el.classList.remove(cls),560)}

function watchMarketPulse(){const usd=$('#mrUsd');if(!usd)return;let last='',first=true;const react=()=>{const v=usd.textContent.trim();if(!v||v==='—'||v===last)return;last=v;if(first){first=false;setTimeout(()=>{const market=$('.mr-market-panel'),core=$('[data-core="preview"]')||$('.mr-core-card .mr-core-wrap');if(market&&core){runCause(market,core);pulse(core.closest('.mr-core-preview')||core,'mr-cause-hit')}},180)}else{const market=$('.mr-market-panel'),core=$('[data-core="preview"]')||$('.mr-core-card .mr-core-wrap');if(market&&core){runCause(market,core);pulse(core.closest('.mr-core-preview')||core,'mr-cause-hit')}}};new MutationObserver(react).observe(usd,{subtree:true,childList:true,characterData:true});react()}
})();