(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const capture=(name,props={})=>{try{window.gtag?.('event',name,props)}catch(_){}try{window.scosCapture?.(name,props)}catch(_){}};
const SUPPORT='https://donate.stripe.com/9B65kFfLBfF96G6gSVgrS04';
let shown=false,last='',engaged=false,started=false,resultSent=false;
const style=document.createElement('style');style.textContent=`.mr-relief{margin:12px 0 0;padding:16px;border:1px solid rgba(124,231,194,.16);border-radius:18px;background:linear-gradient(145deg,rgba(124,231,194,.065),rgba(255,255,255,.012));display:none}.mr-relief.show{display:block}.mr-relief small{display:block;color:#7ce7c2;font-size:8px;letter-spacing:.14em}.mr-relief h3{margin:7px 0 4px;font-size:22px;letter-spacing:-.035em}.mr-relief p{margin:5px 0;color:#8fa09b;font-size:11px;line-height:1.65}.mr-relief .annual{font-size:13px;color:#dce9e5}.mr-relief>a{display:inline-flex;margin-top:10px;padding:9px 13px;border:1px solid rgba(124,231,194,.2);border-radius:999px;color:#dff8ef;text-decoration:none;font-size:11px;background:rgba(124,231,194,.06)}.mr-clarity{margin:12px 0 0;display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.mr-clarity>div{padding:12px;border:1px solid rgba(208,230,224,.1);border-radius:14px;background:rgba(255,255,255,.012)}.mr-clarity small{display:block;color:#7ce7c2;font-size:7px;letter-spacing:.13em}.mr-clarity b{display:block;margin-top:5px;font-size:11px;font-weight:560}.mr-clarity p{margin:5px 0 0;color:#71847f;font-size:8px;line-height:1.55}.mr-proof{margin:10px 0 2px;padding:11px 12px;border:1px solid rgba(208,230,224,.09);border-radius:13px;background:rgba(255,255,255,.01);display:flex;align-items:center;gap:8px;flex-wrap:wrap}.mr-proof span{color:#71847f;font-size:8px;line-height:1.45;margin-right:auto}.mr-proof a{color:#9deed2;text-decoration:none;font-size:8px;border-bottom:1px solid rgba(157,238,210,.2);padding:3px 0}@media(max-width:720px){.mr-relief{padding:14px}.mr-relief h3{font-size:19px}.mr-clarity{grid-template-columns:1fr}.mr-proof{align-items:flex-start}.mr-proof span{flex-basis:100%}}`;document.head.appendChild(style);
function lang(){return document.documentElement.lang==='en'?'en':'ja'}
function money(text){const raw=String(text||'').trim(),n=Number(raw.replace(/[^0-9.-]/g,''));return Number.isFinite(n)?{n,raw}:null}
function shock(){const tiles=$$('#mrResultGrid .mr-result-tile');const t=tiles.find(x=>/shock|月間/i.test($('small',x)?.textContent||''))||tiles[1];return money($('b',t)?.textContent)}
function fmtAnnual(m){const v=Math.abs(m.n)*12;if(/^¥/.test(m.raw)||lang()==='ja')return '¥'+Math.round(v).toLocaleString('ja-JP');const symbol=(m.raw.match(/^[$€£]/)||['$'])[0];return symbol+Math.round(v).toLocaleString('en-US')}
function clarity(box){if($('.mr-clarity',box))return;const c=document.createElement('div');c.className='mr-clarity';box.insertBefore(c,$('a',box));syncClarity(c)}
function syncClarity(c){if(!c)return;const ja=lang()==='ja';c.innerHTML=ja?'<div><small>こんな人向け</small><b>市場の変化が「自分の家計にいくら響くか」分からない</b><p>相場予想ではなく、自分の入力値に対する家計インパクトを整理します。</p></div><div><small>このページで得るもの</small><b>月間Impact・年間換算・Cash Runway</b><p>どこが一番効いているか分かれば、このUtilityの役目は完了です。</p></div><div><small>しないこと</small><b>投資推奨・相場予測・借入判断はしません</b><p>透明なStress条件で比較する判断補助に限定します。</p></div>':'<div><small>FOR WHO</small><b>You know markets moved, but not what that means for your household</b><p>This translates your own inputs into household impact instead of forecasting markets.</p></div><div><small>YOU LEAVE WITH</small><b>Monthly impact, annualized impact, and cash runway</b><p>The job is done when you can see what matters most to your household.</p></div><div><small>NOT THIS</small><b>No investment picks, market forecasts, or borrowing decisions</b><p>This is a transparent stress-case comparison tool only.</p></div>'}
function proof(box){if($('.mr-proof',box))return;const p=document.createElement('div');p.className='mr-proof';const tip=$('a',box);box.insertBefore(p,tip);syncProof(p)}
function syncProof(p){if(!p)return;const ja=lang()==='ja';p.innerHTML=ja?'<span>計算は入力値と選択したStress条件をブラウザ内で比較します。</span><a href="/methodology.html">計算方針</a><a href="/sources.html">Source</a><a href="/privacy.html">Privacy</a>':'<span>Calculations compare your inputs with the selected stress case in your browser.</span><a href="/methodology.html">Methodology</a><a href="/sources.html">Sources</a><a href="/privacy.html">Privacy</a>'}
function mount(){const result=$('.mr-result-card')||$('#mrResultGrid')?.parentElement;if(!result||$('.mr-relief',result))return false;const box=document.createElement('section');box.className='mr-relief';box.setAttribute('aria-live','polite');box.innerHTML='<small></small><h3></h3><p class="annual"></p><p class="note"></p><a target="_blank" rel="noopener noreferrer"></a>';result.appendChild(box);$('a',box).href=SUPPORT;$('a',box).addEventListener('click',()=>capture('tip_clicked',{site:'money_resilience',amount:500,currency:'jpy',moment:'after_result',version:'relief-v1'}));clarity(box);proof(box);return true}
function sync(){mount();const box=$('.mr-relief');if(!box||!engaged)return;const m=shock();if(!m||!m.raw||m.raw==='—')return;if(!resultSent){resultSent=true;capture('input_complete',{site:'money_resilience',version:'relief-v1'});capture('result_generated',{site:'money_resilience',version:'relief-v1'})}const key=m.raw+'|'+lang();if(key===last&&box.classList.contains('show'))return;last=key;const ja=lang()==='ja',annual=fmtAnnual(m);$('small',box).textContent='MONEY IMPACT';$('h3',box).textContent=ja?`このStressでは月間 ${m.raw} の影響`:`This stress case changes your month by ${m.raw}`;$('.annual',box).textContent=ja?`年間換算の目安：${annual}`:`Rough annualized impact: ${annual}`;$('.note',box).textContent=ja?'入力した数字と現在のStress条件を単純換算した比較値です。予測や金融助言ではありません。結果は無料で完了しています。':`A transparent comparison based on your inputs and the selected stress case — not a forecast or financial advice. Your result is already complete and free.`;syncClarity($('.mr-clarity',box));syncProof($('.mr-proof',box));$('a[target="_blank"]',box).textContent=ja?'役立ったら ¥500 Tip':'Helped you see the impact? Leave a small tip';box.classList.add('show');if(!shown){shown=true;capture('tip_shown',{site:'money_resilience',moment:'after_result',version:'relief-v1'});capture('result_success',{site:'money_resilience',version:'relief-v1'})}}
function engage(){engaged=true;if(!started){started=true;capture('utility_start',{site:'money_resilience',version:'relief-v1'})}requestAnimationFrame(sync)}
function markEngaged(e){if(!e.target.closest('#mrWorkspace,.mr-controls-card,.mr-shock-wrap'))return;engage()}
let tries=0;const boot=setInterval(()=>{tries++;if($('#mrResultGrid')){clearInterval(boot);mount();const grid=$('#mrResultGrid');new MutationObserver(()=>requestAnimationFrame(sync)).observe(grid,{subtree:true,childList:true,characterData:true,attributes:true});document.addEventListener('input',markEngaged,true);document.addEventListener('change',markEngaged,true);document.addEventListener('click',e=>{if(e.target.closest('[data-lang]')){setTimeout(()=>{syncClarity($('.mr-clarity'));syncProof($('.mr-proof'));sync()},40)};if(e.target.closest('#mrWorkspace button,.mr-controls-card button,.mr-shock-wrap button')){engage();setTimeout(sync,20)}})}else if(tries>150)clearInterval(boot)},80);
})();