import React from 'react';
import {registerRoot, Composition, AbsoluteFill, Sequence, interpolate, useCurrentFrame, Easing, staticFile} from 'remotion';
import {Audio} from '@remotion/media';

const C={bg:'#06090d',silver:'#eef2f7',mid:'#b7c2d0',muted:'#768497',blue:'#7aa5e0',card:'#0e131b',border:'#293548'};
const serif={fontFamily:'Arial, Helvetica, sans-serif'};
const Grid=()=> <AbsoluteFill style={{backgroundColor:C.bg,backgroundImage:'linear-gradient(rgba(255,255,255,.025) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.025) 1px,transparent 1px)',backgroundSize:'48px 48px'}}/>;
const Brand=()=> <div style={{position:'absolute',top:88,left:88,fontSize:26,fontWeight:700,letterSpacing:5,color:C.mid}}>STRATUM PRAXIS</div>;
const Footer=({n,right})=><><div style={{position:'absolute',left:88,bottom:250,fontSize:22,color:C.muted}}>{String(n).padStart(2,'0')} / 05</div><div style={{position:'absolute',right:88,bottom:250,fontSize:22,color:C.muted}}>{right}</div></>;
const FadeMove=({children,from=0,dy=28})=>{const f=useCurrentFrame();const o=interpolate(f,[from,from+16],[0,1],{extrapolateRight:'clamp'});const y=interpolate(f,[from,from+20],[dy,0],{extrapolateRight:'clamp',easing:Easing.bezier(.16,1,.3,1)});return <div style={{opacity:o,translate:`0 ${y}px`}}>{children}</div>}
const Shell=({children})=><AbsoluteFill style={{...serif,backgroundColor:C.bg,color:C.silver,overflow:'hidden'}}><Grid/><div style={{position:'absolute',width:720,height:720,borderRadius:'50%',right:-180,top:-260,background:'rgba(55,112,180,.12)',filter:'blur(90px)'}}/><Brand/>{children}</AbsoluteFill>;

const S1=()=>{const f=useCurrentFrame();const pulse=1+Math.sin(f/8)*.015;const nodes=[['Claude',120,950],['Codex',700,1085],['Cursor',180,1420],['Agent N',700,1500]];return <Shell><div style={{position:'absolute',left:88,top:250,color:C.blue,fontSize:24,fontWeight:700,letterSpacing:3}}>CROSS-AGENT OPERATIONS</div><FadeMove from={2}><div style={{position:'absolute',left:88,top:335,fontSize:96,fontWeight:800,lineHeight:.98,letterSpacing:-4}}>MORE AGENTS<br/>≠ MORE CONTROL.</div></FadeMove><FadeMove from={12}><div style={{position:'absolute',left:88,top:570,width:860,fontSize:34,lineHeight:1.45,color:C.mid}}>When roles, permissions, handoffs, and stop conditions drift, coordination becomes the bottleneck.</div></FadeMove><div style={{position:'absolute',inset:0,scale:pulse}}>{nodes.map(([t,x,y])=><div key={t} style={{position:'absolute',left:x,top:y,width:220,height:112,borderRadius:24,border:'2px solid #3a4658',background:C.card,display:'flex',alignItems:'center',justifyContent:'center',fontSize:29,fontWeight:700}}>{t}</div>)}</div><div style={{position:'absolute',left:510,top:1140,width:58,height:58,borderRadius:'50%',border:'3px solid #e07070',color:'#f5a5a5',fontSize:30,fontWeight:800,display:'grid',placeItems:'center'}}>!</div><Footer n={1} right="Operational clarity before agent sprawl."/></Shell>}
const Card=({label,value})=><div style={{height:235,borderRadius:24,border:`2px solid ${C.border}`,background:C.card,padding:28}}><div style={{fontSize:20,letterSpacing:2,color:C.blue,fontWeight:700}}>{label}</div><div style={{fontSize:34,fontWeight:800,lineHeight:1.15,marginTop:18}}>{value}</div></div>;
const S2=()=> <Shell><div style={{position:'absolute',left:88,top:245,color:C.blue,fontSize:24,fontWeight:700,letterSpacing:3}}>WHERE MULTI-AGENT STACKS BREAK</div><FadeMove><div style={{position:'absolute',left:88,top:322,fontSize:76,fontWeight:800,lineHeight:1.04,letterSpacing:-3}}>THE FAILURE ISN'T<br/>THE MODEL.</div></FadeMove><div style={{position:'absolute',left:88,top:530,fontSize:34,color:C.mid}}>It's the operating layer around the models.</div><div style={{position:'absolute',left:88,top:690,width:904,display:'grid',gridTemplateColumns:'1fr 1fr',gap:20}}>{[['ROLES','Who owns the task?'],['PERMISSIONS','What can each agent change?'],['HUMAN GATES','Where must a person approve?'],['STOP RULES','When does automation halt?'],['BUDGET','Who controls token & quota spend?'],['CONFLICTS','Which policy wins?']].map(([a,b])=><Card key={a} label={a} value={b}/>)}</div><Footer n={2} right="Control surface > tool count."/></Shell>;
const S3=()=>{const f=useCurrentFrame();return <Shell><div style={{position:'absolute',left:88,top:245,color:C.blue,fontSize:24,fontWeight:700,letterSpacing:3}}>THE OPERATING LAYER</div><div style={{position:'absolute',left:88,top:322,fontSize:82,fontWeight:800,lineHeight:1.02,letterSpacing:-3}}>ONE POLICY.<br/>MULTIPLE AGENTS.</div><div style={{position:'absolute',left:88,top:535,width:860,fontSize:32,lineHeight:1.4,color:C.mid}}>A shared control system that keeps agent-specific behavior aligned with one operating contract.</div><div style={{position:'absolute',left:88,top:790,width:904,display:'flex',flexDirection:'column',gap:20}}>{[['Claude adapter','agent-specific rules'],['Codex adapter','execution boundaries'],['AGENTS.md MASTER POLICY','source of operational truth'],['Cursor adapter','coding context'],['Human Gate Matrix','approval map']].map(([a,b],i)=><div key={a} style={{height:125,borderRadius:22,border:`${i===2?3:2}px solid ${i===2?C.blue:C.border}`,background:C.card,padding:'0 30px',display:'flex',alignItems:'center',justifyContent:'space-between',scale:i===2?interpolate(f,[10,28],[.96,1.03],{extrapolateRight:'clamp'}):1}}><strong style={{fontSize:31,color:i===2?C.blue:C.silver}}>{a}</strong><span style={{fontSize:20,color:C.muted}}>{b}</span></div>)}</div><Footer n={3} right="Keep the brain. Change the agent."/></Shell>}
const S4=()=> <Shell><div style={{position:'absolute',left:88,top:235,color:C.blue,fontSize:24,fontWeight:700,letterSpacing:3}}>INSIDE THE KIT</div><div style={{position:'absolute',left:88,top:312,fontSize:82,fontWeight:800,lineHeight:1.02,letterSpacing:-3}}>BUILT FOR<br/>REAL OPERATIONS.</div><div style={{position:'absolute',left:88,top:520,width:830,fontSize:31,lineHeight:1.4,color:C.mid}}>A compact control layer for teams of AI tools — not another prompt bundle.</div><div style={{position:'absolute',left:88,top:690,width:904,display:'grid',gridTemplateColumns:'1fr 1fr',gap:20}}>{[['01','Master policy'],['02','Agent adapters'],['03','Conflict checks'],['04','Human gates'],['05','Budget + quota guard'],['06','Migration score']].map(([a,b])=><Card key={a} label={a} value={b}/>)}</div><Footer n={4} right="v1.0 · Personal license"/></Shell>;
const S5=()=>{const f=useCurrentFrame();const glow=interpolate(f,[35,60],[0,1],{extrapolateRight:'clamp'});return <Shell><div style={{position:'absolute',left:88,top:235,color:C.blue,fontSize:24,fontWeight:700,letterSpacing:3}}>CROSS-AGENT OPERATING KIT</div><div style={{position:'absolute',left:88,top:320,width:900,fontSize:72,fontWeight:800,lineHeight:1.05,letterSpacing:-3}}>FIX THE OPERATING LAYER<br/>BEFORE ADDING<br/>ANOTHER AGENT.</div><div style={{position:'absolute',left:88,top:690,fontSize:170,fontWeight:800,letterSpacing:-7}}>$69</div><div style={{position:'absolute',left:88,top:870,color:C.blue,fontSize:26,fontWeight:700,letterSpacing:3}}>PERSONAL</div><div style={{position:'absolute',left:88,top:930,width:850,fontSize:32,lineHeight:1.45,color:C.mid}}>One purchaser · own projects · full v1.0 kit · verified buyer workspace.</div><div style={{position:'absolute',left:88,top:1165,width:482,height:122,borderRadius:22,background:'#dae4f0',color:'#06080b',display:'grid',placeItems:'center',fontSize:34,fontWeight:800,boxShadow:`0 0 ${50*glow}px rgba(122,165,224,.45)`}}>GET PERSONAL →</div><div style={{position:'absolute',left:88,top:1335,fontSize:25,color:'#9fb0c7'}}>stratumpraxis.com/<br/>cross-agent-operating-kit.html</div><div style={{position:'absolute',left:88,top:1450,fontSize:24,color:C.muted}}>One operating contract for a multi-agent stack.</div><Footer n={5} right="STRATUM PRAXIS"/></Shell>}

const scenes=[S1,S2,S3,S4,S5];
const sceneFrames=[180,180,210,210,240];
const CrossAgentAd=()=>{let start=0;return <AbsoluteFill><Audio src={staticFile('narration.mp3')} volume={0.95}/>{scenes.map((Scene,i)=>{const from=start;start+=sceneFrames[i];return <Sequence key={i} from={from} durationInFrames={sceneFrames[i]}><Scene/></Sequence>})}</AbsoluteFill>}
const Root=()=> <Composition id="CrossAgentAd" component={CrossAgentAd} durationInFrames={sceneFrames.reduce((a,b)=>a+b,0)} fps={30} width={1080} height={1920}/>;
registerRoot(Root);
