import baseWorker from './ai-consultant-worker.js';

const te=new TextEncoder(),td=new TextDecoder();
const COUNCIL={priceId:'price_1U8I2UJMK7zFs9975vOb3wPD',paymentLinkId:'plink_1U8I2cJMK7zFs997FUnqeZ3Z',amount:2900,currency:'usd'};
function json(body,status=200,headers={}){return new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store',...headers}})}
function b64u(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function fromB64u(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const raw=atob(s);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function sign(secret,sid){const payload=b64u(te.encode(JSON.stringify({sid,product:'council',exp:Date.now()+30*24*60*60*1000})));const key=await crypto.subtle.importKey('raw',te.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('HMAC',key,te.encode('council-access-v1|'+payload));return payload+'.'+b64u(new Uint8Array(sig))}
async function verify(secret,token){try{const [payload,sig]=String(token||'').split('.');if(!payload||!sig)return null;const key=await crypto.subtle.importKey('raw',te.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['verify']);const ok=await crypto.subtle.verify('HMAC',key,fromB64u(sig),te.encode('council-access-v1|'+payload));if(!ok)return null;const p=JSON.parse(td.decode(fromB64u(payload)));return p.sid&&p.product==='council'&&p.exp>Date.now()?p:null}catch{return null}}
async function getSession(env,sid){const r=await fetch(`https://api.stripe.com/v1/checkout/sessions/${encodeURIComponent(sid)}?expand[]=line_items.data.price`,{headers:{Authorization:`Bearer ${env.STRIPE_SECRET_KEY}`}});const s=await r.json();if(!r.ok)throw new Error('Stripe verification failed');return s}
function paidFor(s){const li=s.line_items?.data||[];return s.payment_status==='paid'&&s.mode==='payment'&&li.length===1&&li[0]?.price?.id===COUNCIL.priceId&&Number(li[0]?.quantity||0)===1&&Number(s.amount_total)===COUNCIL.amount&&String(s.currency||'').toLowerCase()===COUNCIL.currency&&s.payment_link===COUNCIL.paymentLinkId}
async function anonId(sid){const d=await crypto.subtle.digest('SHA-256',te.encode('council-purchase-v1|'+sid));return b64u(new Uint8Array(d)).slice(0,32)}
async function capture(env,sid,event,properties={}){if(!env.POSTHOG_PROJECT_TOKEN||!sid)return;try{const id=await anonId(sid);await fetch('https://us.i.posthog.com/i/v0/e/',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({api_key:env.POSTHOG_PROJECT_TOKEN,distinct_id:'verified_'+id,event,properties:{product:'ai_council_builder',source:'verified_worker','$process_person_profile':false,'$insert_id':`council-${event}-${id}`,...properties}})})}catch{}}
async function activate(env,s){if(s.metadata?.council_activated_at)return false;const body=new URLSearchParams();body.set('metadata[council_activated_at]',new Date().toISOString());body.set('metadata[council_activation]','1');body.set('metadata[council_activation_source]','secure_workspace_v1');const r=await fetch(`https://api.stripe.com/v1/checkout/sessions/${encodeURIComponent(s.id)}`,{method:'POST',headers:{Authorization:`Bearer ${env.STRIPE_SECRET_KEY}`,'Content-Type':'application/x-www-form-urlencoded'},body});return r.ok}
function workspace(){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>AI Council Builder — Private Workspace</title><style>:root{--b:#090b0e;--p:#12171d;--p2:#171d24;--l:#2b333c;--t:#f3f5f7;--m:#aab2bc;--a:#edf1f5;--ok:#bfe7c8;--w:#ffd4a2}*{box-sizing:border-box}body{margin:0;background:var(--b);color:var(--t);font:15px/1.58 Inter,system-ui,sans-serif}.w{max-width:1040px;margin:auto;padding:28px 18px 90px}.brand{font-size:12px;letter-spacing:.14em;color:var(--m)}h1{font-size:clamp(38px,7vw,70px);line-height:1;margin:18px 0}.lead,.m{color:var(--m)}.card{background:var(--p);border:1px solid var(--l);border-radius:18px;padding:20px;margin:14px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.controls{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}label{display:block;font-weight:700;font-size:13px}select,input,textarea{width:100%;margin-top:6px;background:#0c1014;color:var(--t);border:1px solid var(--l);border-radius:10px;padding:11px}textarea{min-height:140px;font:13px/1.5 ui-monospace,SFMono-Regular,monospace}.btn{border:0;border-radius:10px;padding:10px 13px;font-weight:800;cursor:pointer}.primary{background:var(--a);color:#090b0e}.copy{margin-top:8px}.pill{display:inline-block;padding:5px 9px;border:1px solid var(--l);border-radius:999px;margin:3px;font-size:12px}.role{background:var(--p2);border:1px solid var(--l);border-radius:13px;padding:14px;margin:9px 0}.role b{display:block}.safe{border-left:3px solid var(--ok)}.warning{border-left:3px solid var(--w)}table{width:100%;border-collapse:collapse}th,td{text-align:left;border-bottom:1px solid var(--l);padding:9px 6px}td input{margin:0}.hide{display:none}.summary{white-space:pre-wrap;background:#0c1014;border-radius:12px;padding:14px}.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}.tabs a{text-decoration:none;border:1px solid var(--l);padding:8px 10px;border-radius:999px}.small{font-size:12px}@media(max-width:760px){.grid,.controls{grid-template-columns:1fr}table{font-size:12px}}</style></head><body><main class="w"><div class="brand">STRATUM PRAXIS · VERIFIED PURCHASE · AI COUNCIL BUILDER v1.0</div><h1>Build the smallest AI team that improves the decision.</h1><p class="lead">Use this workspace locally in your browser. It does not connect to third-party AI accounts, store API keys, or execute actions for you.</p><nav class="tabs"><a href="#planner">Stack planner</a><a href="#roles">Council roles</a><a href="#meetings">Meeting modes</a><a href="#spend">Spend optimizer</a><a href="#safety">Safety</a></nav>
<section id="planner" class="card"><h2>1 · AI Stack Planner</h2><p class="m">Choose the work pattern. The recommendation is a workflow structure, not a claim that one named provider is universally best.</p><div class="controls"><label>Main job<select id="goal"><option value="create">Writing / creation</option><option value="research">Research / synthesis</option><option value="decision">Strategy / decisions</option><option value="build">Coding / building</option><option value="mixed">Mixed knowledge work</option></select></label><label>Cost of a wrong answer<select id="risk"><option value="low">Low</option><option value="medium">Moderate</option><option value="high">Material to the work</option></select></label><label>Process tolerance<select id="process"><option value="simple">Minimal</option><option value="balanced">Balanced</option><option value="rigorous">Rigorous</option></select></label><label>Subscription preference<select id="budget"><option value="one">Prefer one paid AI</option><option value="two">Two if roles differ</option><option value="fit">Optimize for fit</option></select></label><label>Need fresh web evidence?<select id="fresh"><option value="no">Not usually</option><option value="yes">Often</option></select></label><label>Need code/tool execution?<select id="tools"><option value="no">No</option><option value="yes">Yes</option></select></label></div><button id="buildPlan" class="btn primary" style="margin-top:14px">Build my structure</button><div id="plan" class="role"></div></section>
<section id="roles" class="card"><h2>2 · Core Council Roles</h2><p class="m">Assign these roles to different models or separate fresh conversations. Different role instructions matter more than simply duplicating the same prompt five times.</p><div id="roleList"></div></section>
<section id="meetings" class="card"><h2>3 · Meeting Modes</h2><div class="grid"><div class="role"><b>Fast Check · 2 roles</b><p>Builder → Skeptic. Use for ordinary drafts where a second set of eyes is enough.</p></div><div class="role"><b>Evidence Check · 3 roles</b><p>Scout → Builder → Verifier. Use when factual freshness matters.</p></div><div class="role"><b>Decision Council · 5 roles</b><p>Scout → Builder → Skeptic → Verifier → Judge. Use for consequential business decisions.</p></div><div class="role"><b>Red-Team Council · 4 roles</b><p>Builder → Skeptic → Failure Simulator → Judge. Use before shipping workflows or policies.</p></div></div><h3>Universal handoff protocol</h3><textarea id="protocol" readonly>1. Give every role the same objective, constraints, and source material.\n2. First-pass roles work independently before seeing other answers.\n3. The Skeptic attacks assumptions, missing evidence, hidden costs, and failure modes.\n4. The Verifier labels claims as verified, uncertain, or unsupported and requests primary evidence where practical.\n5. The Judge receives the original objective plus all outputs, resolves disagreements explicitly, and produces one decision memo.\n6. Human reviews the memo before any real-world action.</textarea><button class="btn copy" data-copy="protocol">Copy protocol</button></section>
<section class="card"><h2>4 · Final Decision Memo</h2><textarea id="memo" readonly>DECISION MEMO\n\nObjective:\nConstraints:\nOptions considered:\nEvidence that matters:\nStrongest argument for the chosen option:\nStrongest argument against it:\nUnresolved uncertainty:\nWhat would change the decision:\nReversible next step:\nHuman approval required before:\nDecision:</textarea><button class="btn copy" data-copy="memo">Copy memo template</button></section>
<section id="spend" class="card"><h2>5 · Bonus: AI Subscription Overlap & Spend Optimizer</h2><p class="m">Enter your own monthly costs and the single job each subscription is supposed to own. Nothing is sent anywhere. This tool flags apparent overlap; it does not cancel subscriptions or provide financial advice.</p><table><thead><tr><th>AI/service</th><th>Monthly $</th><th>Primary job</th><th>Use</th></tr></thead><tbody id="rows"></tbody></table><button id="addRow" class="btn" style="margin-top:10px">Add subscription</button> <button id="auditSpend" class="btn primary">Review overlap</button><div id="spendResult" class="summary" style="margin-top:14px">Add your subscriptions to review them.</div></section>
<section id="safety" class="card safe"><h2>6 · Safe-use boundary</h2><p>This toolkit is intended for general productivity, research organization, drafting, software planning and ordinary business decision support. Keep a human decision-maker in control.</p><ul><li>Do not use this workflow as the sole basis for medical, legal, financial, credit, employment, eligibility, emergency or other high-stakes decisions.</li><li>Do not paste passwords, API keys, payment-card data, government IDs, medical records or unnecessary personal data into AI services.</li><li>Verify material factual claims and current third-party pricing/features before relying on them.</li><li>For agents that can send, publish, buy, delete or modify external systems: use least privilege, approval gates, retry ceilings and rollback/kill-switch controls.</li></ul></section>
<section class="card warning"><h2>What you purchased</h2><p>A self-serve planning and prompt toolkit. You did not purchase third-party AI access, an accuracy guarantee, implementation services, account management, subscription cancellation, professional advice, ongoing updates or support. Third-party services can change independently.</p></section><p class="m small">Access token expires after 30 days; access can be reopened from the original Stripe completion URL while purchase verification remains available.</p></main><script>
const roles=[
['Scout','Find relevant evidence before proposing a solution. Separate current facts, assumptions and unknowns. Prefer primary/recent sources when freshness matters. Return only evidence that could change the decision.'],
['Builder','Create the strongest practical answer to the objective using the supplied evidence and constraints. State trade-offs. Do not hide uncertainty or invent proof.'],
['Skeptic','Assume the current proposal may be wrong. Attack demand assumptions, missing constraints, hidden costs, false confidence, circular reasoning, operational burden and simpler alternatives. Do not be contrarian without a reason.'],
['Verifier','Audit material factual claims. Label each as verified, uncertain, outdated-risk or unsupported. Distinguish direct evidence from inference. Do not treat model agreement as verification.'],
['Judge','Review the original objective plus independent outputs. Resolve disagreements using evidence and constraints, not majority vote. Produce one decision, key uncertainty, reversibility plan and the smallest next test.'],
['Failure Simulator','Imagine the plan has failed three months from now. Identify plausible failure paths, trigger signals, blast radius, prevention, detection and rollback. Focus on realistic operational failures.'],
['Cost Keeper','Identify duplicated tools, recurring fees, token/API exposure, human review time and maintenance burden. Prefer the smallest stack that meets the objective.']
];
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
document.getElementById('roleList').innerHTML=roles.map((r,i)=>'<div class="role"><b>'+esc(r[0])+'</b><textarea id="role'+i+'" readonly>ROLE: '+esc(r[0])+'\n\n'+esc(r[1])+'\n\nINPUT YOU WILL RECEIVE:\nObjective, constraints, source material, and any prior role output explicitly provided.\n\nOUTPUT:\nConcise findings, evidence/assumptions, risks, and handoff to the next role.</textarea><button class="btn copy" data-copy="role'+i+'">Copy '+esc(r[0])+' prompt</button></div>').join('');
function plan(){const g=goal.value,r=risk.value,p=process.value,b=budget.value,f=fresh.value,t=tools.value;let names=[];if(p==='simple'&&r==='low')names=['Builder'];else if(r==='high'||p==='rigorous')names=['Scout','Builder','Skeptic','Verifier','Judge'];else names=['Builder','Skeptic','Judge'];if(f==='yes'&&!names.includes('Scout'))names.unshift('Scout');if(t==='yes'&&!names.includes('Failure Simulator'))names.splice(-1,0,'Failure Simulator');if(b==='one')names=names.map((x,i)=>x+(i?' (fresh conversation is enough if you only pay for one AI)':''));const note=g==='research'?'Prioritize source access and citation checking.':g==='build'?'Keep code execution separate from final approval; test in a reversible environment.':g==='decision'?'Make the Judge explicit and require the strongest counterargument.':'Use a second role only where it changes quality enough to justify the extra step.';document.getElementById('plan').innerHTML='<b>Recommended structure</b><p>'+names.map(x=>'<span class="pill">'+esc(x)+'</span>').join('')+'</p><p>'+esc(note)+'</p><p class="m">Provider choice: start with the AI you already have. Add another paid service only if a distinct job remains unmet after testing. Re-check current provider features and prices at the time you choose.</p>'}
document.getElementById('buildPlan').onclick=plan;plan();
document.addEventListener('click',async e=>{const b=e.target.closest('[data-copy]');if(!b)return;const el=document.getElementById(b.dataset.copy);await navigator.clipboard.writeText(el.value||el.textContent);const old=b.textContent;b.textContent='Copied';setTimeout(()=>b.textContent=old,900)});
const tbody=document.getElementById('rows');function addRow(name='',cost='',job=''){const tr=document.createElement('tr');tr.innerHTML='<td><input class="sname" placeholder="Service" value="'+esc(name)+'"></td><td><input class="scost" type="number" min="0" step="0.01" placeholder="20" value="'+esc(cost)+'"></td><td><input class="sjob" placeholder="e.g. research" value="'+esc(job)+'"></td><td><button class="btn remove">×</button></td>';tbody.appendChild(tr);tr.querySelector('.remove').onclick=()=>tr.remove()}
addRow();addRow();document.getElementById('addRow').onclick=()=>addRow();document.getElementById('auditSpend').onclick=()=>{const data=[...tbody.querySelectorAll('tr')].map(tr=>({name:tr.querySelector('.sname').value.trim(),cost:Number(tr.querySelector('.scost').value||0),job:tr.querySelector('.sjob').value.trim().toLowerCase()})).filter(x=>x.name||x.cost||x.job);const total=data.reduce((a,x)=>a+x.cost,0);const jobs={};data.forEach(x=>{if(x.job)(jobs[x.job]||(jobs[x.job]=[])).push(x)});const overlap=Object.entries(jobs).filter(([,x])=>x.length>1);let text='Monthly AI spend entered: $'+total.toFixed(2)+'\nAnnualized: $'+(total*12).toFixed(2)+'\n';if(overlap.length){text+='\nPossible role overlap:\n'+overlap.map(([j,x])=>'• '+j+': '+x.map(y=>y.name||'unnamed').join(', ')).join('\n')+'\n\nReview question: does each overlapping subscription deliver a distinct benefit you actually use?';}else{text+='\nNo duplicate primary-job labels detected. This does not prove the stack is efficient; review actual usage before changing any subscription.'}text+='\n\nNo cancellation is performed. Verify current plan terms and billing before making changes.';document.getElementById('spendResult').textContent=text};
</script></body></html>`}

export default {async fetch(request,env,ctx){const url=new URL(request.url);if(!url.pathname.startsWith('/council/'))return baseWorker.fetch(request,env,ctx);const allowed=request.headers.get('Origin');const cors=allowed==='https://stratumpraxis.com'?{'Access-Control-Allow-Origin':allowed,'Vary':'Origin'}:{};if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{...cors,'Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'POST,GET,OPTIONS'}});try{if(request.method==='POST'&&url.pathname==='/council/login'){const body=await request.json();const sid=String(body.session_id||'');const email=String(body.email||'').trim().toLowerCase();if(!sid.startsWith('cs_')||!email)return json({error:'Checkout Session ID and purchase email are required'},400,cors);const s=await getSession(env,sid);if(!paidFor(s))return json({error:'AI Council Builder payment was not confirmed'},402,cors);const paidEmail=String(s.customer_details?.email||s.customer_email||'').trim().toLowerCase();if(!paidEmail||paidEmail!==email)return json({error:'Purchase email does not match'},403,cors);await capture(env,s.id,'revenue_verified',{amount_total:s.amount_total,currency:s.currency});const token=await sign(env.STRIPE_SECRET_KEY,s.id);return json({authorized:true,workspace_url:`${url.origin}/council/workspace?token=${encodeURIComponent(token)}`},200,cors)}if(request.method==='GET'&&url.pathname==='/council/workspace'){const p=await verify(env.STRIPE_SECRET_KEY,url.searchParams.get('token'));if(!p)return new Response('Access token is invalid or expired.',{status:401,headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store','X-Robots-Tag':'noindex,nofollow,noarchive'}});const s=await getSession(env,p.sid);if(!paidFor(s))return new Response('Purchase could not be verified.',{status:402,headers:{'Content-Type':'text/plain; charset=utf-8','Cache-Control':'no-store'}});const tracked=await activate(env,s);if(tracked)await capture(env,s.id,'activation',{activation_source:'secure_workspace_v1'});return new Response(workspace(),{status:200,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store, private','X-Robots-Tag':'noindex, nofollow, noarchive','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src 'self' data:; base-uri 'none'; frame-ancestors 'none'; form-action 'none'",'X-Council-Activation-Tracked':tracked?'1':'0'}})}return json({error:'Not found'},404,cors)}catch{return json({error:'Verification error'},500,cors)}}};