import React from 'react';
import {AbsoluteFill,Audio,Composition,Sequence,interpolate,registerRoot,staticFile,useCurrentFrame} from 'remotion';

const BG='#05070b', CYAN='#79f2e6', RED='#ff5f6d', GOLD='#ffd166', WHITE='#f7fafc', MUTED='#aab6c2';
const clamp={extrapolateLeft:'clamp',extrapolateRight:'clamp'};
const fade=(f,a,b)=>interpolate(f,[a,b],[0,1],clamp);

const Grid=()=> <AbsoluteFill style={{backgroundImage:'linear-gradient(rgba(121,242,230,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(121,242,230,.08) 1px,transparent 1px)',backgroundSize:'72px 72px'}}/>;
const Glow=({x,y,c=CYAN,s=500})=><div style={{position:'absolute',left:x,top:y,width:s,height:s,borderRadius:'50%',background:c,opacity:.12,filter:'blur(120px)'}}/>;
const Header=({eyebrow,lines,accent=CYAN})=>{const f=useCurrentFrame(); return <div style={{position:'absolute',left:76,right:76,top:120,opacity:fade(f,3,14)}}><div style={{fontSize:21,letterSpacing:4,color:MUTED,fontWeight:800}}>{eyebrow}</div><div style={{marginTop:22,fontSize:66,lineHeight:1.02,fontWeight:950,color:WHITE,textTransform:'uppercase'}}>{lines.map((l,i)=><div key={l} style={{color:i===lines.length-1?accent:WHITE}}>{l}</div>)}</div></div>};
const Footer=({text})=><div style={{position:'absolute',left:76,right:76,bottom:150,fontSize:22,letterSpacing:2,color:MUTED,fontWeight:700}}>{text}</div>;

const Threshold=()=>{const f=useCurrentFrame(); const p=interpolate(f,[20,180],[0,.92],clamp); return <AbsoluteFill style={{background:'radial-gradient(circle at 70% 25%,#12313b 0%,#081017 42%,#040609 100%)'}}><Grid/><Glow x={560} y={100}/><Header eyebrow='FORWELLE / AI CONTROL' lines={['OPENAI JUST','TRIGGERED A NEW','SAFETY THRESHOLD']} accent={GOLD}/><div style={{position:'absolute',left:100,right:100,top:720,height:92,borderRadius:46,background:'#ffffff12',overflow:'hidden',border:'1px solid #ffffff1c'}}><div style={{height:'100%',width:`${p*100}%`,background:`linear-gradient(90deg,${CYAN},${GOLD},${RED})`,boxShadow:`0 0 35px ${RED}`}}/></div><div style={{position:'absolute',left:100,right:100,top:835,display:'flex',justifyContent:'space-between',color:MUTED,fontSize:18,letterSpacing:2}}><span>CAPABILITY</span><span>CRITICAL CYBER</span></div><Footer text='THE FIRST TIME THIS GUARDRAIL HAS BEEN TRIGGERED'/></AbsoluteFill>};

const Astra=()=>{const f=useCurrentFrame(); const nodes=Array.from({length:18},(_,i)=>({x:110+(i%3)*320,y:660+Math.floor(i/3)*160})); return <AbsoluteFill style={{background:'linear-gradient(150deg,#07131a,#07090e 58%,#160b10)'}}><Grid/><Glow x={-120} y={700}/><Glow x={690} y={250} c={RED}/><Header eyebrow='UPCOMING MODEL / ASTRA' lines={['FIND','EXPLOIT','CYBER FLAWS']} accent={RED}/>{nodes.map((n,i)=>{const on=fade(f,4+i*3,18+i*3); const hot=(i%5===0); return <div key={i} style={{position:'absolute',left:n.x,top:n.y,width:76,height:76,borderRadius:19,opacity:on,background:hot?'#251015':'#0b171f',border:`2px solid ${hot?RED:CYAN}88`,boxShadow:`0 0 28px ${hot?RED:CYAN}33`}}/>})}<Footer text='STRONGER GUARDRAILS REQUIRED BEFORE RELEASE'/></AbsoluteFill>};

const Breach=()=>{const f=useCurrentFrame(); const sweep=interpolate(f,[0,205],[-80,2050],clamp); return <AbsoluteFill style={{background:'radial-gradient(circle at 50% 55%,#1b1116,#08090d 55%,#040507)'}}><Grid/><Glow x={-130} y={550} c={RED}/><Header eyebrow='WHY THIS MATTERS' lines={['THE RISK IS','NO LONGER','THEORETICAL']} accent={RED}/><div style={{position:'absolute',left:90,right:90,top:760,padding:34,borderRadius:28,background:'#110b10dd',border:`1px solid ${RED}88`}}><div style={{fontSize:24,color:MUTED,letterSpacing:2}}>JULY 2026</div><div style={{fontSize:51,fontWeight:950,color:WHITE,marginTop:12}}>HUGGING FACE</div><div style={{fontSize:27,fontWeight:850,color:RED,marginTop:9}}>BREACHED DURING CYBER EVALUATIONS</div></div><div style={{position:'absolute',left:0,right:0,top:sweep,height:3,background:`linear-gradient(90deg,transparent,${RED},transparent)`,boxShadow:`0 0 36px ${RED}`}}/><Footer text='ASTRA WAS NOT INVOLVED IN THAT INCIDENT'/></AbsoluteFill>};

const First=()=>{const f=useCurrentFrame(); const ring=interpolate(f,[10,190],[0,360],clamp); return <AbsoluteFill style={{background:'linear-gradient(160deg,#061018,#09101a 45%,#0b080d)'}}><Grid/><Glow x={570} y={620}/><Header eyebrow='THE IMPORTANT DISTINCTION' lines={['ASTRA IS','THE FIRST MODEL','TO CROSS IT']} accent={GOLD}/><div style={{position:'absolute',left:305,top:780,width:470,height:470,borderRadius:'50%',border:`8px solid ${GOLD}`,boxShadow:`0 0 90px ${GOLD}33`,transform:`rotate(${ring}deg)`}}/><div style={{position:'absolute',left:305,top:780,width:470,height:470,display:'grid',placeItems:'center',textAlign:'center'}}><div><div style={{fontSize:23,color:MUTED,letterSpacing:3}}>OPENAI THRESHOLD</div><div style={{fontSize:70,fontWeight:950,color:GOLD,marginTop:16}}>CRITICAL</div><div style={{fontSize:29,fontWeight:900,color:WHITE}}>CYBER CAPABILITY</div></div></div><Footer text='CAPABILITY HAS BECOME A RELEASE CONSTRAINT'/></AbsoluteFill>};

const End=()=>{const f=useCurrentFrame(); const y=interpolate(f,[20,150],[40,0],clamp); return <AbsoluteFill style={{background:'radial-gradient(circle at 50% 55%,#0e2528,#070a0e 50%,#030405)'}}><Grid/><Glow x={290} y={720}/><Header eyebrow='THE HIDDEN SHIFT' lines={['THE NEXT AI','BOTTLENECK ISN’T','INTELLIGENCE']} accent={CYAN}/><div style={{position:'absolute',left:76,right:76,top:780,transform:`translateY(${y}px)`,padding:'30px 34px',borderRadius:28,background:'#0b151ce8',border:`1px solid ${GOLD}77`,textAlign:'center'}}><div style={{fontSize:22,color:MUTED,letterSpacing:3}}>IT'S</div><div style={{fontSize:94,fontWeight:950,color:GOLD,letterSpacing:2}}>CONTROL.</div></div><Footer text='FOLLOW FORWELLE — THE STRUCTURE BEHIND THE HEADLINE'/></AbsoluteFill>};

const Main=()=> <AbsoluteFill style={{background:BG,fontFamily:'Arial, Helvetica, sans-serif'}}><Audio src={staticFile('astra/bgm.wav')} volume={0.48}/><Audio src={staticFile('astra/narration.mp3')} volume={1}/><Sequence from={0} durationInFrames={210}><Threshold/></Sequence><Sequence from={210} durationInFrames={210}><Astra/></Sequence><Sequence from={420} durationInFrames={210}><Breach/></Sequence><Sequence from={630} durationInFrames={210}><First/></Sequence><Sequence from={840} durationInFrames={210}><End/></Sequence></AbsoluteFill>;
const Root=()=> <Composition id='ForwelleAstraShort' component={Main} durationInFrames={1050} fps={30} width={1080} height={1920}/>;
registerRoot(Root);
